// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { OverviewResponse, CreateSeasonResponse, CreateSeasonBody, UpdateSeasonResponse, UpdateSeasonBody, DeleteSeasonResponse, CreatePriceRuleResponse, CreatePriceRuleBody, UpdatePriceRuleResponse, UpdatePriceRuleBody, DeletePriceRuleResponse, CreatePolicyResponse, CreatePolicyBody, UpdatePolicyResponse, UpdatePolicyBody, CreateRatePlanResponse, CreateRatePlanBody, UpdateRatePlanResponse, UpdateRatePlanBody } from './types';

const motortarifaService = {
  async overview(tenantId: string): Promise<OverviewResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/tarifas`);
    return data;
  },

  async createSeason(tenantId: string, body: CreateSeasonBody): Promise<CreateSeasonResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/tarifas/seasons`, body);
    return data;
  },

  async updateSeason(tenantId: string, id: string, body: UpdateSeasonBody): Promise<UpdateSeasonResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/tarifas/seasons/${id}`, body);
    return data;
  },

  async deleteSeason(tenantId: string, id: string): Promise<DeleteSeasonResponse> {
    const { data } = await apiClient.delete(`/api/motor/${tenantId}/tarifas/seasons/${id}`);
    return data;
  },

  async createPriceRule(tenantId: string, body: CreatePriceRuleBody): Promise<CreatePriceRuleResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/tarifas/price-rules`, body);
    return data;
  },

  async updatePriceRule(tenantId: string, id: string, body: UpdatePriceRuleBody): Promise<UpdatePriceRuleResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/tarifas/price-rules/${id}`, body);
    return data;
  },

  async deletePriceRule(tenantId: string, id: string): Promise<DeletePriceRuleResponse> {
    const { data } = await apiClient.delete(`/api/motor/${tenantId}/tarifas/price-rules/${id}`);
    return data;
  },

  async createPolicy(tenantId: string, body: CreatePolicyBody): Promise<CreatePolicyResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/tarifas/policies`, body);
    return data;
  },

  async updatePolicy(tenantId: string, id: string, body: UpdatePolicyBody): Promise<UpdatePolicyResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/tarifas/policies/${id}`, body);
    return data;
  },

  async createRatePlan(tenantId: string, body: CreateRatePlanBody): Promise<CreateRatePlanResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/tarifas/rate-plans`, body);
    return data;
  },

  async updateRatePlan(tenantId: string, id: string, body: UpdateRatePlanBody): Promise<UpdateRatePlanResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/tarifas/rate-plans/${id}`, body);
    return data;
  },
};

export default motortarifaService;
