// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateSeasonDto = Record<string, unknown>;

export type UpdateSeasonDto = Record<string, unknown>;

export type CreatePriceRuleDto = Record<string, unknown>;

export type UpdatePriceRuleDto = Record<string, unknown>;

export type CreatePolicyDto = Record<string, unknown>;

export type UpdatePolicyDto = Record<string, unknown>;

export type CreateRatePlanDto = Record<string, unknown>;

export type UpdateRatePlanDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/tarifas — response */
export type OverviewResponse = unknown;

/** POST /motor/{tenantId}/tarifas/seasons — response */
export type CreateSeasonResponse = unknown;
/** POST /motor/{tenantId}/tarifas/seasons — payload */
export type CreateSeasonBody = CreateSeasonDto;

/** PUT /motor/{tenantId}/tarifas/seasons/{id} — response */
export type UpdateSeasonResponse = unknown;
/** PUT /motor/{tenantId}/tarifas/seasons/{id} — payload */
export type UpdateSeasonBody = UpdateSeasonDto;

/** DELETE /motor/{tenantId}/tarifas/seasons/{id} — response */
export type DeleteSeasonResponse = unknown;

/** POST /motor/{tenantId}/tarifas/price-rules — response */
export type CreatePriceRuleResponse = unknown;
/** POST /motor/{tenantId}/tarifas/price-rules — payload */
export type CreatePriceRuleBody = CreatePriceRuleDto;

/** PUT /motor/{tenantId}/tarifas/price-rules/{id} — response */
export type UpdatePriceRuleResponse = unknown;
/** PUT /motor/{tenantId}/tarifas/price-rules/{id} — payload */
export type UpdatePriceRuleBody = UpdatePriceRuleDto;

/** DELETE /motor/{tenantId}/tarifas/price-rules/{id} — response */
export type DeletePriceRuleResponse = unknown;

/** POST /motor/{tenantId}/tarifas/policies — response */
export type CreatePolicyResponse = unknown;
/** POST /motor/{tenantId}/tarifas/policies — payload */
export type CreatePolicyBody = CreatePolicyDto;

/** PUT /motor/{tenantId}/tarifas/policies/{id} — response */
export type UpdatePolicyResponse = unknown;
/** PUT /motor/{tenantId}/tarifas/policies/{id} — payload */
export type UpdatePolicyBody = UpdatePolicyDto;

/** POST /motor/{tenantId}/tarifas/rate-plans — response */
export type CreateRatePlanResponse = unknown;
/** POST /motor/{tenantId}/tarifas/rate-plans — payload */
export type CreateRatePlanBody = CreateRatePlanDto;

/** PUT /motor/{tenantId}/tarifas/rate-plans/{id} — response */
export type UpdateRatePlanResponse = unknown;
/** PUT /motor/{tenantId}/tarifas/rate-plans/{id} — payload */
export type UpdateRatePlanBody = UpdateRatePlanDto;
