// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, ListResponse, ListParams, FindOneResponse, UpdateResponse, UpdateBody, RemoveResponse, GetAssetsResponse, GetAssetsParams, RemoveAssetResponse } from './types';

const cmsMediaCollectionsService = {
  /** Create a new media collection */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/cms/collections', body);
    return data;
  },

  /** List media collections with filtering */
  async list(params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/cms/collections', { params });
    return data;
  },

  /** Get media collection by ID */
  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/cms/collections/${id}`);
    return data;
  },

  /** Update media collection */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/cms/collections/${id}`, body);
    return data;
  },

  /** Delete media collection (only if empty) */
  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/cms/collections/${id}`);
    return data;
  },

  /** List all assets in a collection */
  async getAssets(id: string, params: GetAssetsParams = {} as GetAssetsParams): Promise<GetAssetsResponse> {
    const { data } = await apiClient.get(`/api/cms/collections/${id}/assets`, { params });
    return data;
  },

  /** Delete a specific asset from a collection */
  async removeAsset(id: string, assetId: string): Promise<RemoveAssetResponse> {
    const { data } = await apiClient.delete(`/api/cms/collections/${id}/assets/${assetId}`);
    return data;
  },
};

export default cmsMediaCollectionsService;
