// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateCollectionDTO {
  /** Collection name */
  name: string;
  /** Unique slug for the collection (per tenant) */
  slug: string;
  /** Collection description */
  description?: string;
  /** Collection type */
  type: 'image' | 'document' | 'video' | 'audio' | 'mixed';
  /** Maximum file size in bytes */
  max_file_size?: number;
  /** Allowed mime types (supports wildcards like image/*) */
  allowed_mime_types?: string[];
  /** Maximum number of items allowed in collection */
  max_items?: number;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/collections — response */
export type CreateResponse = unknown;
/** POST /cms/collections — payload */
export type CreateBody = CreateCollectionDTO;

/** GET /cms/collections — response */
export type ListResponse = unknown;
/** GET /cms/collections — query params */
export interface ListParams {
  type?: 'image' | 'document' | 'video' | 'audio' | 'mixed';
  page?: number;
  limit?: number;
}

/** GET /cms/collections/{id} — response */
export type FindOneResponse = unknown;

/** PUT /cms/collections/{id} — response */
export type UpdateResponse = unknown;
/** PUT /cms/collections/{id} — payload */
export interface UpdateBody {
  name?: string;
  description?: string;
  type?: 'image' | 'document' | 'video' | 'audio' | 'mixed';
  max_file_size?: number;
  allowed_mime_types?: string[];
  max_items?: number;
}

/** DELETE /cms/collections/{id} — response */
export type RemoveResponse = unknown;

/** GET /cms/collections/{id}/assets — response */
export type GetAssetsResponse = unknown;
/** GET /cms/collections/{id}/assets — query params */
export interface GetAssetsParams {
  page?: number;
  limit?: number;
}

/** DELETE /cms/collections/{id}/assets/{assetId} — response */
export type RemoveAssetResponse = unknown;
