// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindByClientIdResponse, FindByClientIdParams, GetReactivationListResponse, FindByIdResponse, AddStayResponse, AddStayBody } from './types';

const guestcrmService = {
  async create(clientId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/guests/${clientId}`, body);
    return data;
  },

  async findByClientId(clientId: string, params: FindByClientIdParams = {} as FindByClientIdParams): Promise<FindByClientIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/guests/${clientId}`, { params });
    return data;
  },

  async getReactivationList(clientId: string): Promise<GetReactivationListResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/guests/${clientId}/reactivation`);
    return data;
  },

  async findById(guestId: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/guests/guest/${guestId}`);
    return data;
  },

  async addStay(guestId: string, body: AddStayBody): Promise<AddStayResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/guests/guest/${guestId}/stays`, body);
    return data;
  },
};

export default guestcrmService;
