// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateGuestDto = Record<string, unknown>;

export type CreateGuestStayDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/guests/{clientId} — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/guests/{clientId} — payload */
export type CreateBody = CreateGuestDto;

/** GET /admin/hotel-portal/guests/{clientId} — response */
export type FindByClientIdResponse = unknown;
/** GET /admin/hotel-portal/guests/{clientId} — query params */
export interface FindByClientIdParams {
  page: string;
  limit: string;
  segment: string;
}

/** GET /admin/hotel-portal/guests/{clientId}/reactivation — response */
export type GetReactivationListResponse = unknown;

/** GET /admin/hotel-portal/guests/guest/{guestId} — response */
export type FindByIdResponse = unknown;

/** POST /admin/hotel-portal/guests/guest/{guestId}/stays — response */
export type AddStayResponse = unknown;
/** POST /admin/hotel-portal/guests/guest/{guestId}/stays — payload */
export type AddStayBody = CreateGuestStayDto;
