// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { UploadResponse, UploadBody, FindAllResponse, DeleteResponse, ReorderResponse, ReorderBody } from './types';

const cmsImageManagementService = {
  /** Upload an image for an article */
  async upload(articleId: string, body: UploadBody): Promise<UploadResponse> {
    const { data } = await apiClient.post(`/api/cms/articles/${articleId}/images`, body);
    return data;
  },

  /** List all images for an article */
  async findAll(articleId: string): Promise<FindAllResponse> {
    const { data } = await apiClient.get(`/api/cms/articles/${articleId}/images`);
    return data;
  },

  /** Delete a specific image from an article */
  async delete(articleId: string, imageId: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/cms/articles/${articleId}/images/${imageId}`);
    return data;
  },

  /** Reorder images within an article */
  async reorder(articleId: string, body: ReorderBody): Promise<ReorderResponse> {
    const { data } = await apiClient.put(`/api/cms/articles/${articleId}/images/reorder`, body);
    return data;
  },
};

export default cmsImageManagementService;
