// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface ImageOrderItem {
  /** Image ID */
  id: number;
  /** Display order position */
  display_order: number;
}

export interface ReorderImagesDTO {
  /** Array of image IDs with their new display order */
  order: ImageOrderItem[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/articles/{articleId}/images — response */
export type UploadResponse = unknown;
/** POST /cms/articles/{articleId}/images — payload */
export interface UploadBody {
  /** Image file. Allowed types and size limit are defined by the article-images collection. */
  file: string;
  /** Accessibility text for the image. Max 255 chars. Highly recommended for SEO and accessibility. */
  alt_text?: string;
}

/** GET /cms/articles/{articleId}/images — response */
export type FindAllResponse = unknown;

/** DELETE /cms/articles/{articleId}/images/{imageId} — response */
export type DeleteResponse = unknown;

/** PUT /cms/articles/{articleId}/images/reorder — response */
export type ReorderResponse = unknown;
/** PUT /cms/articles/{articleId}/images/reorder — payload */
export type ReorderBody = ReorderImagesDTO;
