// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { HandleStripeWebhookResponse } from './types';

const webhooksService = {
  /** Stripe webhook endpoint (per-tenant) */
  async handleStripeWebhook(tenantId: string): Promise<HandleStripeWebhookResponse> {
    const { data } = await apiClient.post(`/api/webhooks/stripe/${tenantId}`);
    return data;
  },
};

export default webhooksService;
