// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CaptureLeadResponse, CaptureLeadBody } from './types';

const leadCaptureService = {
  /** Submit a lead to a collection */
  async captureLead(slug: string, body: CaptureLeadBody): Promise<CaptureLeadResponse> {
    const { data } = await apiClient.post(`/api/leads/collect/${slug}`, body);
    return data;
  },
};

export default leadCaptureService;
