// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateLeadDto {
  /** Lead name */
  name?: string;
  /** Lead email address */
  email?: string;
  /** Lead phone number */
  phone_number?: string;
  /** Lead origin */
  origin?: 1 | 2 | 3 | 4 | 5 | 6;
  /** Lead origin source */
  origin_font?: string;
  /** Description or notes about the lead */
  description?: string;
  /** Additional lead data in JSON format */
  data: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /leads/collect/{slug} — response */
export type CaptureLeadResponse = unknown;
/** POST /leads/collect/{slug} — payload */
export type CaptureLeadBody = CreateLeadDto;
