// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListProductsResponse, CalculateCostResponse, CreateLeadCheckoutResponse, CreateLeadCheckoutBody, CreateCartCheckoutResponse, CreateCartCheckoutBody } from './types';

const publicBbProductsService = {
  /** List all active B2B products (public) */
  async listProducts(): Promise<ListProductsResponse> {
    const { data } = await apiClient.get('/api/public/b2b/products');
    return data;
  },

  /** Calcular custo total de um produto B2B (público) */
  async calculateCost(productId: string): Promise<CalculateCostResponse> {
    const { data } = await apiClient.post(`/api/public/b2b/products/${productId}/calculate-cost`);
    return data;
  },

  /** Create checkout for a single product (public) */
  async createLeadCheckout(productId: string, body: CreateLeadCheckoutBody): Promise<CreateLeadCheckoutResponse> {
    const { data } = await apiClient.post(`/api/public/b2b/products/${productId}/checkout`, body);
    return data;
  },

  /** Create cart checkout with multiple products (public) */
  async createCartCheckout(body: CreateCartCheckoutBody): Promise<CreateCartCheckoutResponse> {
    const { data } = await apiClient.post('/api/public/b2b/checkout', body);
    return data;
  },
};

export default publicBbProductsService;
