// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface OrderCostBreakdownResponseDTO {
  /** Preço base em centavos */
  basePrice: number;
  /** Valor do chip cost em centavos (basePrice × chipCostPercent%) */
  chipCostAmount: number;
  /** Frete em centavos (fixo por pedido, 0 para digitais) */
  shippingFee: number;
  /** Total final em centavos */
  total: number;
  currency: string;
  /** Percentual de chip cost aplicado */
  chipCostPercent: number;
  chipCostSource: 'product' | 'category' | 'global' | 'none';
  shippingFeeSource: 'product' | 'category' | 'global' | 'none';
  requiresShipping: boolean;
}

export interface CreateLeadCheckoutDTO {
  /** ID do produto B2B */
  productId: string;
  /** Nome completo do lead */
  leadName: string;
  /** Email do lead */
  leadEmail: string;
  /** Telefone do lead (formato E.164) */
  leadPhone: string;
}

export interface CartItemDTO {
  /** ID do produto B2B */
  productId: string;
  /** Quantidade */
  quantity: number;
}

export interface CreateCartCheckoutDTO {
  /** Lista de produtos e quantidades */
  items: CartItemDTO[];
  /** Nome completo do lead */
  leadName: string;
  /** Email do lead */
  leadEmail: string;
  /** Telefone do lead (formato E.164) */
  leadPhone: string;
  /** Códigos de cupom (opcionais) */
  couponCodes?: string[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /public/b2b/products — response */
export type ListProductsResponse = unknown;

/** POST /public/b2b/products/{productId}/calculate-cost — response */
export type CalculateCostResponse = OrderCostBreakdownResponseDTO;

/** POST /public/b2b/products/{productId}/checkout — response */
export type CreateLeadCheckoutResponse = unknown;
/** POST /public/b2b/products/{productId}/checkout — payload */
export type CreateLeadCheckoutBody = CreateLeadCheckoutDTO;

/** POST /public/b2b/checkout — response */
export type CreateCartCheckoutResponse = unknown;
/** POST /public/b2b/checkout — payload */
export type CreateCartCheckoutBody = CreateCartCheckoutDTO;
