// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, FindAllParams, FindOneResponse, UpdateResponse, UpdateBody, DeleteResponse, PublishResponse, PublishBody, UpdatePublishedAtResponse, UpdatePublishedAtBody, ArchiveResponse, UnarchiveResponse } from './types';

const cmsArticleManagementService = {
  /** Create a new article in draft status */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/cms/articles', body);
    return data;
  },

  /** List articles */
  async findAll(params: FindAllParams = {} as FindAllParams): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/cms/articles', { params });
    return data;
  },

  /** Get a single article by ID */
  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/cms/articles/${id}`);
    return data;
  },

  /** Update article content and metadata */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/cms/articles/${id}`, body);
    return data;
  },

  /** Delete an article and its associated relations */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/cms/articles/${id}`);
    return data;
  },

  /** Publish or schedule an article */
  async publish(id: string, body: PublishBody): Promise<PublishResponse> {
    const { data } = await apiClient.post(`/api/cms/articles/${id}/publish`, body);
    return data;
  },

  /** Edit the published_at date of a published or scheduled article */
  async updatePublishedAt(id: string, body: UpdatePublishedAtBody): Promise<UpdatePublishedAtResponse> {
    const { data } = await apiClient.patch(`/api/cms/articles/${id}/published-at`, body);
    return data;
  },

  /** Transition article status from published to archived */
  async archive(articleId: string): Promise<ArchiveResponse> {
    const { data } = await apiClient.post(`/api/cms/articles/${articleId}/archive`);
    return data;
  },

  /** Restore an archived article back to published status */
  async unarchive(articleId: string): Promise<UnarchiveResponse> {
    const { data } = await apiClient.post(`/api/cms/articles/${articleId}/unarchive`);
    return data;
  },
};

export default cmsArticleManagementService;
