// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateArticleDTO {
  /** Display title shown to readers */
  displayTitle: string;
  /** Article language in ll_cc format */
  language?: string;
  /** SEO meta title (max 60 characters) */
  metaTitle: string;
  /** SEO meta description (max 160 characters) */
  metaDescription?: string;
  /** SEO focus keyword */
  focusKeyword?: string;
  /** Article content (markdown) */
  content: string;
  /** URL-safe slug (lowercase, hyphens only) */
  slug: string;
  /** Cover image MediaAsset ID (UUID) */
  coverImageId?: string;
  /** Author ID (UUID) */
  authorId: string;
  /** Blog ID (UUID) */
  blogId: string;
}

export interface UpdateArticleDTO {
  /** Display title shown to readers */
  displayTitle?: string;
  /** Article language in ll_cc format */
  language?: string;
  /** SEO meta title (max 60 characters) */
  metaTitle?: string;
  /** SEO meta description (max 160 characters) */
  metaDescription?: string;
  /** SEO focus keyword */
  focusKeyword?: string;
  /** Article content (markdown) */
  content?: string;
  /** URL-safe slug (lowercase, hyphens only) */
  slug?: string;
  /** Cover image MediaAsset ID (UUID) */
  coverImageId?: string;
  /** Author ID (UUID) */
  authorId?: string;
}

export interface PublishArticleDTO {
  /** Schedule publication for a future date/time (ISO 8601). If omitted or in the past, publishes immediately. */
  scheduledAt?: string;
}

export interface UpdatePublishedAtDTO {
  /** New published_at timestamp (ISO 8601). If in the future, article is rescheduled. If in the past, corrects the publication date. */
  publishedAt: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/articles — response */
export type CreateResponse = unknown;
/** POST /cms/articles — payload */
export type CreateBody = CreateArticleDTO;

/** GET /cms/articles — response */
export type FindAllResponse = unknown;
/** GET /cms/articles — query params */
export interface FindAllParams {
  blogId: string;
  status: string;
  page: string;
  limit: string;
}

/** GET /cms/articles/{id} — response */
export type FindOneResponse = unknown;

/** PUT /cms/articles/{id} — response */
export type UpdateResponse = unknown;
/** PUT /cms/articles/{id} — payload */
export type UpdateBody = UpdateArticleDTO;

/** DELETE /cms/articles/{id} — response */
export type DeleteResponse = unknown;

/** POST /cms/articles/{id}/publish — response */
export type PublishResponse = unknown;
/** POST /cms/articles/{id}/publish — payload */
export type PublishBody = PublishArticleDTO;

/** PATCH /cms/articles/{id}/published-at — response */
export type UpdatePublishedAtResponse = unknown;
/** PATCH /cms/articles/{id}/published-at — payload */
export type UpdatePublishedAtBody = UpdatePublishedAtDTO;

/** POST /cms/articles/{articleId}/archive — response */
export type ArchiveResponse = unknown;

/** POST /cms/articles/{articleId}/unarchive — response */
export type UnarchiveResponse = unknown;
