// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, ListParams, CreateResponse, CreateBody, GenerateLinkResponse, GenerateLinkParams, GetByIdResponse, UpdateResponse, UpdateBody, RemoveResponse } from './types';

const adminCouponsService = {
  /** Listar cupons do tenant (paginado) */
  async list(params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/admin/coupons', { params });
    return data;
  },

  /** Criar cupom */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/admin/coupons', body);
    return data;
  },

  /** Gerar link de cupom */
  async generateLink(id: string, params: GenerateLinkParams = {} as GenerateLinkParams): Promise<GenerateLinkResponse> {
    const { data } = await apiClient.get(`/api/admin/coupons/${id}/link`, { params });
    return data;
  },

  /** Buscar cupom por ID */
  async getById(id: string): Promise<GetByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/coupons/${id}`);
    return data;
  },

  /** Atualizar cupom */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/admin/coupons/${id}`, body);
    return data;
  },

  /** Desativar cupom (soft-delete) */
  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/admin/coupons/${id}`);
    return data;
  },
};

export default adminCouponsService;
