// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface ProductOverrideDTO {
  /** ID do produto */
  productId: string;
  discountType: 'percentage' | 'fixed_amount';
  /** Percentual (0-100) ou valor em centavos. Deve ser > 0. */
  discountValue: number;
}

export interface CreateCouponDTO {
  /** Código único do cupom (convertido para maiúsculas) */
  code: string;
  name: string;
  description?: string;
  discountType: 'percentage' | 'fixed_amount';
  /** Percentual (0-100) ou valor em centavos */
  discountValue: number;
  scope: 'order' | 'product' | 'category';
  productIds?: string[];
  categoryIds?: string[];
  appliesTo: 'b2b' | 'b2c' | 'b2c_recurring' | 'b2c_one_time' | 'both';
  cumulative?: boolean;
  /** Valor mínimo do pedido em centavos */
  minOrderAmount?: number;
  /** Desconto máximo em centavos */
  maxDiscountAmount?: number;
  /** Máximo de resgates (null = ilimitado) */
  maxRedemptions?: number;
  expiresAt?: string;
  /** Descontos específicos por produto. Válido apenas quando scope="product". Cada productId deve estar presente em productIds. O discountValue global serve como fallback para produtos sem override. */
  productOverrides?: ProductOverrideDTO[];
}

export interface UpdateCouponDTO {
  name?: string;
  description?: string;
  discountValue?: number;
  productIds?: string[];
  categoryIds?: string[];
  appliesTo?: 'b2b' | 'b2c' | 'b2c_recurring' | 'b2c_one_time' | 'both';
  cumulative?: boolean;
  minOrderAmount?: number;
  maxDiscountAmount?: number;
  maxRedemptions?: number;
  expiresAt?: string;
  active?: boolean;
  /** Descontos específicos por produto. Válido apenas quando scope="product". Passe null ou array vazio para remover todos os overrides. */
  productOverrides?: ProductOverrideDTO[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/coupons — response */
export type ListResponse = unknown;
/** GET /admin/coupons — query params */
export interface ListParams {
  page?: number;
  limit?: number;
}

/** POST /admin/coupons — response */
export type CreateResponse = unknown;
/** POST /admin/coupons — payload */
export type CreateBody = CreateCouponDTO;

/** GET /admin/coupons/{id}/link — response */
export type GenerateLinkResponse = unknown;
/** GET /admin/coupons/{id}/link — query params */
export interface GenerateLinkParams {
  /** URL base do site (ex: https://meusite.com/checkout) */
  baseUrl?: string;
}

/** GET /admin/coupons/{id} — response */
export type GetByIdResponse = unknown;

/** PUT /admin/coupons/{id} — response */
export type UpdateResponse = unknown;
/** PUT /admin/coupons/{id} — payload */
export type UpdateBody = UpdateCouponDTO;

/** DELETE /admin/coupons/{id} — response */
export type RemoveResponse = unknown;
