// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, ListResponse } from './types';

const adminactivitylogService = {
  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/activities`, body);
    return data;
  },

  async list(tenantId: string): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/activities`);
    return data;
  },
};

export default adminactivitylogService;
