// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateActivityLogDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/activities — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/activities — payload */
export type CreateBody = CreateActivityLogDto;

/** GET /admin/hotel-portal/{tenantId}/activities — response */
export type ListResponse = unknown;
