// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { UpsertResponse, UpsertBody, GetResponse } from './types';

const adminAppointmentScheduleConfigurationService = {
  /** Create or update appointment schedule configuration */
  async upsert(body: UpsertBody): Promise<UpsertResponse> {
    const { data } = await apiClient.put('/api/leads/admin/appointments/schedule-config', body);
    return data;
  },

  /** Get appointment schedule configuration */
  async get(): Promise<GetResponse> {
    const { data } = await apiClient.get('/api/leads/admin/appointments/schedule-config');
    return data;
  },
};

export default adminAppointmentScheduleConfigurationService;
