// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UpsertScheduleConfigDto {
  /** Working days (0=Sunday, 6=Saturday) - Legacy format */
  workingDays?: number[];
  /** Work start time in HH:MM format - Legacy format */
  workStartTime?: string;
  /** Work end time in HH:MM format - Legacy format */
  workEndTime?: string;
  /** Lunch start time in HH:MM format - Legacy format */
  lunchStartTime?: string;
  /** Lunch end time in HH:MM format - Legacy format */
  lunchEndTime?: string;
  /** Slot interval in minutes (5-480) */
  slotIntervalMinutes: number;
  /** Capacity per slot (minimum 1) */
  capacityPerSlot: number;
  /** Per-day configuration (keys: 0=Sunday, 1=Monday, ..., 6=Saturday) */
  days?: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** PUT /leads/admin/appointments/schedule-config — response */
export type UpsertResponse = unknown;
/** PUT /leads/admin/appointments/schedule-config — payload */
export type UpsertBody = UpsertScheduleConfigDto;

/** GET /leads/admin/appointments/schedule-config — response */
export type GetResponse = unknown;
