// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindOneResponse, UpdateResponse, UpdateBody, RegenerateKeyResponse, DeactivateResponse, ReactivateResponse } from './types';

const adminbotintegrationconfigService = {
  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/bot-integration-config`, body);
    return data;
  },

  async findOne(tenantId: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/bot-integration-config`);
    return data;
  },

  async update(tenantId: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/bot-integration-config`, body);
    return data;
  },

  async regenerateKey(tenantId: string): Promise<RegenerateKeyResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/bot-integration-config/regenerate-key`);
    return data;
  },

  async deactivate(tenantId: string): Promise<DeactivateResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/bot-integration-config/deactivate`);
    return data;
  },

  async reactivate(tenantId: string): Promise<ReactivateResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/bot-integration-config/reactivate`);
    return data;
  },
};

export default adminbotintegrationconfigService;
