// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateBotIntegrationConfigDto = Record<string, unknown>;

export type UpdateBotIntegrationConfigDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/bot-integration-config — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/bot-integration-config — payload */
export type CreateBody = CreateBotIntegrationConfigDto;

/** GET /admin/hotel-portal/{tenantId}/bot-integration-config — response */
export type FindOneResponse = unknown;

/** PATCH /admin/hotel-portal/{tenantId}/bot-integration-config — response */
export type UpdateResponse = unknown;
/** PATCH /admin/hotel-portal/{tenantId}/bot-integration-config — payload */
export type UpdateBody = UpdateBotIntegrationConfigDto;

/** PATCH /admin/hotel-portal/{tenantId}/bot-integration-config/regenerate-key — response */
export type RegenerateKeyResponse = unknown;

/** PATCH /admin/hotel-portal/{tenantId}/bot-integration-config/deactivate — response */
export type DeactivateResponse = unknown;

/** PATCH /admin/hotel-portal/{tenantId}/bot-integration-config/reactivate — response */
export type ReactivateResponse = unknown;
