// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { UpsertReputationResponse, UpsertReputationBody, GetReputationResponse, GetReputationParams, GetReputationSummaryResponse, UpsertKpiResponse, UpsertKpiBody, GetKpiResponse, GetKpiParams, GetKpiSummaryResponse, UpsertBookingWindowResponse, UpsertBookingWindowBody, GetBookingWindowResponse, GetBookingWindowParams, CreateRateParityResponse, CreateRateParityBody, GetRateParityResponse, GetRateParityParams, GetRateParityViolationsResponse, UpsertBudgetResponse, UpsertBudgetBody, GetBudgetResponse, GetBudgetParams, GetBudgetComparisonResponse, GetBudgetComparisonParams } from './types';

const adminhotelmetricsService = {
  async upsertReputation(clientId: string, body: UpsertReputationBody): Promise<UpsertReputationResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/metrics/${clientId}/reputation`, body);
    return data;
  },

  async getReputation(clientId: string, params: GetReputationParams = {} as GetReputationParams): Promise<GetReputationResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/reputation`, { params });
    return data;
  },

  async getReputationSummary(clientId: string): Promise<GetReputationSummaryResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/reputation/summary`);
    return data;
  },

  async upsertKpi(clientId: string, body: UpsertKpiBody): Promise<UpsertKpiResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/metrics/${clientId}/kpi`, body);
    return data;
  },

  async getKpi(clientId: string, params: GetKpiParams = {} as GetKpiParams): Promise<GetKpiResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/kpi`, { params });
    return data;
  },

  async getKpiSummary(clientId: string): Promise<GetKpiSummaryResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/kpi/summary`);
    return data;
  },

  async upsertBookingWindow(clientId: string, body: UpsertBookingWindowBody): Promise<UpsertBookingWindowResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/metrics/${clientId}/booking-window`, body);
    return data;
  },

  async getBookingWindow(clientId: string, params: GetBookingWindowParams = {} as GetBookingWindowParams): Promise<GetBookingWindowResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/booking-window`, { params });
    return data;
  },

  async createRateParity(clientId: string, body: CreateRateParityBody): Promise<CreateRateParityResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/metrics/${clientId}/rate-parity`, body);
    return data;
  },

  async getRateParity(clientId: string, params: GetRateParityParams = {} as GetRateParityParams): Promise<GetRateParityResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/rate-parity`, { params });
    return data;
  },

  async getRateParityViolations(clientId: string): Promise<GetRateParityViolationsResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/rate-parity/violations`);
    return data;
  },

  async upsertBudget(clientId: string, body: UpsertBudgetBody): Promise<UpsertBudgetResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/metrics/${clientId}/budget`, body);
    return data;
  },

  async getBudget(clientId: string, params: GetBudgetParams = {} as GetBudgetParams): Promise<GetBudgetResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/budget`, { params });
    return data;
  },

  async getBudgetComparison(clientId: string, params: GetBudgetComparisonParams = {} as GetBudgetComparisonParams): Promise<GetBudgetComparisonResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/metrics/${clientId}/budget/comparison`, { params });
    return data;
  },
};

export default adminhotelmetricsService;
