// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type InsertReputationDto = Record<string, unknown>;

export type InsertMonthlyKpiDto = Record<string, unknown>;

export type InsertBookingWindowDto = Record<string, unknown>;

export type InsertRateParityDto = Record<string, unknown>;

export type InsertMarketingBudgetDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/metrics/{clientId}/reputation — response */
export type UpsertReputationResponse = unknown;
/** POST /admin/hotel-portal/metrics/{clientId}/reputation — payload */
export type UpsertReputationBody = InsertReputationDto;

/** GET /admin/hotel-portal/metrics/{clientId}/reputation — response */
export type GetReputationResponse = unknown;
/** GET /admin/hotel-portal/metrics/{clientId}/reputation — query params */
export interface GetReputationParams {
  months: string;
}

/** GET /admin/hotel-portal/metrics/{clientId}/reputation/summary — response */
export type GetReputationSummaryResponse = unknown;

/** POST /admin/hotel-portal/metrics/{clientId}/kpi — response */
export type UpsertKpiResponse = unknown;
/** POST /admin/hotel-portal/metrics/{clientId}/kpi — payload */
export type UpsertKpiBody = InsertMonthlyKpiDto;

/** GET /admin/hotel-portal/metrics/{clientId}/kpi — response */
export type GetKpiResponse = unknown;
/** GET /admin/hotel-portal/metrics/{clientId}/kpi — query params */
export interface GetKpiParams {
  months: string;
}

/** GET /admin/hotel-portal/metrics/{clientId}/kpi/summary — response */
export type GetKpiSummaryResponse = unknown;

/** POST /admin/hotel-portal/metrics/{clientId}/booking-window — response */
export type UpsertBookingWindowResponse = unknown;
/** POST /admin/hotel-portal/metrics/{clientId}/booking-window — payload */
export type UpsertBookingWindowBody = InsertBookingWindowDto;

/** GET /admin/hotel-portal/metrics/{clientId}/booking-window — response */
export type GetBookingWindowResponse = unknown;
/** GET /admin/hotel-portal/metrics/{clientId}/booking-window — query params */
export interface GetBookingWindowParams {
  months: string;
}

/** POST /admin/hotel-portal/metrics/{clientId}/rate-parity — response */
export type CreateRateParityResponse = unknown;
/** POST /admin/hotel-portal/metrics/{clientId}/rate-parity — payload */
export type CreateRateParityBody = InsertRateParityDto;

/** GET /admin/hotel-portal/metrics/{clientId}/rate-parity — response */
export type GetRateParityResponse = unknown;
/** GET /admin/hotel-portal/metrics/{clientId}/rate-parity — query params */
export interface GetRateParityParams {
  page: string;
  limit: string;
}

/** GET /admin/hotel-portal/metrics/{clientId}/rate-parity/violations — response */
export type GetRateParityViolationsResponse = unknown;

/** POST /admin/hotel-portal/metrics/{clientId}/budget — response */
export type UpsertBudgetResponse = unknown;
/** POST /admin/hotel-portal/metrics/{clientId}/budget — payload */
export type UpsertBudgetBody = InsertMarketingBudgetDto;

/** GET /admin/hotel-portal/metrics/{clientId}/budget — response */
export type GetBudgetResponse = unknown;
/** GET /admin/hotel-portal/metrics/{clientId}/budget — query params */
export interface GetBudgetParams {
  months: string;
}

/** GET /admin/hotel-portal/metrics/{clientId}/budget/comparison — response */
export type GetBudgetComparisonResponse = unknown;
/** GET /admin/hotel-portal/metrics/{clientId}/budget/comparison — query params */
export interface GetBudgetComparisonParams {
  month: string;
}
