// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListMovementsResponse, ListMovementsParams, GetTenantSubscriptionResponse, CreateBillingPortalSessionResponse, CreateBillingPortalSessionBody } from './types';

const subscriptionsService = {
  /** List all movements (B2B + B2C combined) */
  async listMovements(params: ListMovementsParams = {} as ListMovementsParams): Promise<ListMovementsResponse> {
    const { data } = await apiClient.get('/api/subscriptions/movements', { params });
    return data;
  },

  /** Get subscription by tenant ID */
  async getTenantSubscription(tenantId: string): Promise<GetTenantSubscriptionResponse> {
    const { data } = await apiClient.get(`/api/subscriptions/tenant/${tenantId}`);
    return data;
  },

  /** Create Stripe Billing Portal session */
  async createBillingPortalSession(body: CreateBillingPortalSessionBody): Promise<CreateBillingPortalSessionResponse> {
    const { data } = await apiClient.post('/api/subscriptions/billing-portal', body);
    return data;
  },
};

export default subscriptionsService;
