// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateBillingPortalSessionDTO {
  /** Tenant ID whose customer will access the billing portal */
  tenantId: string;
  /** URL to redirect the customer back to after they leave the portal */
  returnUrl: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /subscriptions/movements — response */
export type ListMovementsResponse = unknown;
/** GET /subscriptions/movements — query params */
export interface ListMovementsParams {
  source?: 'all' | 'b2b' | 'b2c';
  /** Filter by status (pending, completed, expired, abandoned, etc.) */
  status?: string;
  limit?: number;
  offset?: number;
}

/** GET /subscriptions/tenant/{tenantId} — response */
export type GetTenantSubscriptionResponse = unknown;

/** POST /subscriptions/billing-portal — response */
export type CreateBillingPortalSessionResponse = unknown;
/** POST /subscriptions/billing-portal — payload */
export type CreateBillingPortalSessionBody = CreateBillingPortalSessionDTO;
