// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, PreCreateResponse, PreCreateBody, AuthenticateUserResponse, AuthenticateUserBody, MeResponse, ListCollectionsResponse, GetCollectionContextResponse, GeneratePaymentAccountLinkResponse, CheckoutResponse } from './types';

const userService = {
  /** Create a new user */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/user', body);
    return data;
  },

  /** Pre-create a user (partial registration) */
  async preCreate(body: PreCreateBody): Promise<PreCreateResponse> {
    const { data } = await apiClient.post('/api/user/pre/create', body);
    return data;
  },

  /** Authenticate user */
  async authenticateUser(body: AuthenticateUserBody): Promise<AuthenticateUserResponse> {
    const { data } = await apiClient.post('/api/user/authenticate', body);
    return data;
  },

  /** Get authenticated user data */
  async me(): Promise<MeResponse> {
    const { data } = await apiClient.get('/api/user/me');
    return data;
  },

  /** List collections accessible to the authenticated user */
  async listCollections(): Promise<ListCollectionsResponse> {
    const { data } = await apiClient.get('/api/user/collections');
    return data;
  },

  /** Get authenticated user context inside a collection */
  async getCollectionContext(collectionId: string): Promise<GetCollectionContextResponse> {
    const { data } = await apiClient.get(`/api/user/collections/${collectionId}`);
    return data;
  },

  /** Generate payment account link for the user */
  async generatePaymentAccountLink(): Promise<GeneratePaymentAccountLinkResponse> {
    const { data } = await apiClient.post('/api/user/generate-payment-account-link');
    return data;
  },

  /** Checkout a plan subscription */
  async checkout(slug: string, period: string): Promise<CheckoutResponse> {
    const { data } = await apiClient.post(`/api/user/checkout/${slug}/${period}`);
    return data;
  },
};

export default userService;
