// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateUserDTO {
  /** Full name (min 2 words, letters only) */
  name: string;
  /** User email address */
  email: string;
  /** Phone number */
  phone_number: string;
  /** CPF (Brazilian tax ID) */
  cpf: string;
  /** Password (min 6 characters) */
  password: string;
}

export interface PreCreateUserDTO {
  /** User full name */
  name: string;
  /** User email address */
  email: string;
  /** Phone number */
  phone_number: string;
}

export interface AuthUserDTO {
  /** User email */
  email: string;
  /** User password */
  password: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /user — response */
export type CreateResponse = unknown;
/** POST /user — payload */
export type CreateBody = CreateUserDTO;

/** POST /user/pre/create — response */
export type PreCreateResponse = unknown;
/** POST /user/pre/create — payload */
export type PreCreateBody = PreCreateUserDTO;

/** POST /user/authenticate — response */
export type AuthenticateUserResponse = unknown;
/** POST /user/authenticate — payload */
export type AuthenticateUserBody = AuthUserDTO;

/** GET /user/me — response */
export type MeResponse = unknown;

/** GET /user/collections — response */
export type ListCollectionsResponse = unknown;

/** GET /user/collections/{collectionId} — response */
export type GetCollectionContextResponse = unknown;

/** POST /user/generate-payment-account-link — response */
export type GeneratePaymentAccountLinkResponse = unknown;

/** POST /user/checkout/{slug}/{period} — response */
export type CheckoutResponse = unknown;
