// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, ListParams, CreateResponse, CreateBody, RemoveResponse } from './types';

const motorblockService = {
  async list(tenantId: string, params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/blocks`, { params });
    return data;
  },

  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/blocks`, body);
    return data;
  },

  async remove(tenantId: string, id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/motor/${tenantId}/blocks/${id}`);
    return data;
  },
};

export default motorblockService;
