// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateBlockDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/blocks — response */
export type ListResponse = unknown;
/** GET /motor/{tenantId}/blocks — query params */
export interface ListParams {
  unit_id: string;
  from: string;
  to: string;
}

/** POST /motor/{tenantId}/blocks — response */
export type CreateResponse = unknown;
/** POST /motor/{tenantId}/blocks — payload */
export type CreateBody = CreateBlockDto;

/** DELETE /motor/{tenantId}/blocks/{id} — response */
export type RemoveResponse = unknown;
