// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ModuleResponse, UpdateResponse, UpdateBody } from './types';

const superadminSettingsService = {
  /** One module settings for any tenant (superadmin, merged values only) */
  async module(tenantId: string, module: string): Promise<ModuleResponse> {
    const { data } = await apiClient.get(`/api/settings/tenants/${tenantId}/${module}`);
    return data;
  },

  /** Update module settings for any tenant (superadmin) */
  async update(tenantId: string, module: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/settings/tenants/${tenantId}/${module}`, body);
    return data;
  },
};

export default superadminSettingsService;
