// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UpdateModuleSettingsDto {
  /** Partial map of setting key (camelCase) to new value. Only provided keys are written. Unknown keys → 400, superadmin-scoped keys → 403 (tenant route only). */
  values: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /settings/tenants/{tenantId}/{module} — response */
export type ModuleResponse = Record<string, unknown>;

/** PATCH /settings/tenants/{tenantId}/{module} — response */
export type UpdateResponse = Record<string, unknown>;
/** PATCH /settings/tenants/{tenantId}/{module} — payload */
export type UpdateBody = UpdateModuleSettingsDto;
