// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { AvailabilityResponse, CreateHoldResponse, CreateHoldBody, ReleaseHoldResponse, ConfirmHoldResponse, ConfirmHoldBody, RescheduleResponse, RescheduleBody, CancelResponse, CancelBody } from './types';

const motorbotService = {
  async availability(): Promise<AvailabilityResponse> {
    const { data } = await apiClient.get('/api/motor/availability');
    return data;
  },

  async createHold(body: CreateHoldBody): Promise<CreateHoldResponse> {
    const { data } = await apiClient.post('/api/motor/holds', body);
    return data;
  },

  async releaseHold(id: string): Promise<ReleaseHoldResponse> {
    const { data } = await apiClient.post(`/api/motor/holds/${id}/release`);
    return data;
  },

  async confirmHold(id: string, body: ConfirmHoldBody): Promise<ConfirmHoldResponse> {
    const { data } = await apiClient.post(`/api/motor/holds/${id}/confirm`, body);
    return data;
  },

  async reschedule(id: string, body: RescheduleBody): Promise<RescheduleResponse> {
    const { data } = await apiClient.post(`/api/motor/reservations/${id}/reschedule`, body);
    return data;
  },

  async cancel(id: string, body: CancelBody): Promise<CancelResponse> {
    const { data } = await apiClient.post(`/api/motor/reservations/${id}/cancel`, body);
    return data;
  },
};

export default motorbotService;
