// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateHoldDto = Record<string, unknown>;

export type ConfirmHoldDto = Record<string, unknown>;

export type RescheduleDto = Record<string, unknown>;

export type CancelDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/availability — response */
export type AvailabilityResponse = unknown;

/** POST /motor/holds — response */
export type CreateHoldResponse = unknown;
/** POST /motor/holds — payload */
export type CreateHoldBody = CreateHoldDto;

/** POST /motor/holds/{id}/release — response */
export type ReleaseHoldResponse = unknown;

/** POST /motor/holds/{id}/confirm — response */
export type ConfirmHoldResponse = unknown;
/** POST /motor/holds/{id}/confirm — payload */
export type ConfirmHoldBody = ConfirmHoldDto;

/** POST /motor/reservations/{id}/reschedule — response */
export type RescheduleResponse = unknown;
/** POST /motor/reservations/{id}/reschedule — payload */
export type RescheduleBody = RescheduleDto;

/** POST /motor/reservations/{id}/cancel — response */
export type CancelResponse = unknown;
/** POST /motor/reservations/{id}/cancel — payload */
export type CancelBody = CancelDto;
