// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { AdminListPlansResponse, AdminCreatePlanResponse, AdminCreatePlanBody, AdminUpdatePlanResponse, AdminUpdatePlanBody, AdminArchivePlanResponse, AdminArchivePlanParams, ListActivePlansResponse } from './types';

const plansService = {
  /** List all plans (admin) */
  async adminListPlans(): Promise<AdminListPlansResponse> {
    const { data } = await apiClient.get('/api/plans/admin/list');
    return data;
  },

  /** Create a plan (admin) */
  async adminCreatePlan(body: AdminCreatePlanBody): Promise<AdminCreatePlanResponse> {
    const { data } = await apiClient.post('/api/plans/admin/create', body);
    return data;
  },

  /** Update plan metadata (admin) */
  async adminUpdatePlan(id: string, body: AdminUpdatePlanBody): Promise<AdminUpdatePlanResponse> {
    const { data } = await apiClient.patch(`/api/plans/admin/${id}`, body);
    return data;
  },

  /** Archive a plan (admin) */
  async adminArchivePlan(id: string, params: AdminArchivePlanParams = {} as AdminArchivePlanParams): Promise<AdminArchivePlanResponse> {
    const { data } = await apiClient.delete(`/api/plans/admin/${id}`, { params });
    return data;
  },

  /** List active plans (user) */
  async listActivePlans(): Promise<ListActivePlansResponse> {
    const { data } = await apiClient.get('/api/plans/list');
    return data;
  },
};

export default plansService;
