// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface StripePlanResponseDTO {
  id: string;
  slug: string;
  plan_name: string;
  description?: string;
  stripe_product_id: string;
  stripe_price_id: string;
  stripe_trial_price_id?: string;
  billing_interval: number;
  unit_amount: number;
  currency: string;
  released_credits: number;
  credits_released_trial_period: number;
  guest_limit: number;
  trial_days: number;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateStripePlanDTO {
  /** Tenant ID — used to resolve the Stripe secret key from billing config */
  tenant_id: string;
  /** Unique slug for the plan */
  slug: string;
  plan_name: string;
  description?: string;
  /** Price in cents (e.g. 9990 = R$ 99,90) */
  unit_amount: number;
  currency: 'brl' | 'usd';
  /** 1=weekly | 2=monthly | 3=quarterly | 4=annual */
  billing_interval: 1 | 2 | 3 | 4;
  /** Credits released per billing cycle */
  released_credits: number;
  /** Credits released during trial period */
  credits_released_trial_period?: number;
  /** Trial period in days (0 = no trial) */
  trial_days?: number;
  /** Maximum number of guest users */
  guest_limit?: number;
}

export interface UpdateStripePlanDTO {
  plan_name?: string;
  description?: string;
  released_credits?: number;
  credits_released_trial_period?: number;
  guest_limit?: number;
  trial_days?: number;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /plans/admin/list — response */
export type AdminListPlansResponse = StripePlanResponseDTO[];

/** POST /plans/admin/create — response */
export type AdminCreatePlanResponse = StripePlanResponseDTO;
/** POST /plans/admin/create — payload */
export type AdminCreatePlanBody = CreateStripePlanDTO;

/** PATCH /plans/admin/{id} — response */
export type AdminUpdatePlanResponse = StripePlanResponseDTO;
/** PATCH /plans/admin/{id} — payload */
export type AdminUpdatePlanBody = UpdateStripePlanDTO;

/** DELETE /plans/admin/{id} — response */
export type AdminArchivePlanResponse = unknown;
/** DELETE /plans/admin/{id} — query params */
export interface AdminArchivePlanParams {
  tenant_id: string;
}

/** GET /plans/list — response */
export type ListActivePlansResponse = StripePlanResponseDTO[];
