// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { FindByTenantIdResponse, FindByIdResponse, SubmitForReviewResponse, PublishResponse, PublishBody } from './types';

const admindigestService = {
  async findByTenantId(tenantId: string): Promise<FindByTenantIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/digests`);
    return data;
  },

  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/digests/${id}`);
    return data;
  },

  async submitForReview(id: string): Promise<SubmitForReviewResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/digests/${id}/submit-review`);
    return data;
  },

  async publish(id: string, body: PublishBody): Promise<PublishResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/digests/${id}/publish`, body);
    return data;
  },
};

export default admindigestService;
