// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type PublishDigestDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/hotel-portal/{tenantId}/digests — response */
export type FindByTenantIdResponse = unknown;

/** GET /admin/hotel-portal/digests/{id} — response */
export type FindByIdResponse = unknown;

/** PATCH /admin/hotel-portal/digests/{id}/submit-review — response */
export type SubmitForReviewResponse = unknown;

/** PATCH /admin/hotel-portal/digests/{id}/publish — response */
export type PublishResponse = unknown;
/** PATCH /admin/hotel-portal/digests/{id}/publish — payload */
export type PublishBody = PublishDigestDto;
