// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetResponse, UpdateResponse, UpdateBody } from './types';

const superadminModulesService = {
  /** Module flags for a tenant (superadmin) */
  async get(tenantId: string): Promise<GetResponse> {
    const { data } = await apiClient.get(`/api/settings/tenants/${tenantId}/modules`);
    return data;
  },

  /** Enable/disable modules for a tenant (superadmin) */
  async update(tenantId: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/settings/tenants/${tenantId}/modules`, body);
    return data;
  },
};

export default superadminModulesService;
