// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UpdateTenantModulesDto {
  /** Partial map of gateable module name to enabled flag. Unknown module names → 400. */
  modules: Record<string, boolean>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /settings/tenants/{tenantId}/modules — response */
export type GetResponse = Record<string, boolean>;

/** PATCH /settings/tenants/{tenantId}/modules — response */
export type UpdateResponse = Record<string, boolean>;
/** PATCH /settings/tenants/{tenantId}/modules — payload */
export type UpdateBody = UpdateTenantModulesDto;
