// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, ListParams, CreateResponse, CreateBody, UpdateResponse, UpdateBody, DeleteResponse } from './types';

const adminAppointmentBlockedPeriodsService = {
  /** List blocked periods */
  async list(params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/leads/admin/appointments/blocked-periods', { params });
    return data;
  },

  /** Create a blocked period */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/leads/admin/appointments/blocked-periods', body);
    return data;
  },

  /** Update a blocked period */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/leads/admin/appointments/blocked-periods/${id}`, body);
    return data;
  },

  /** Delete a blocked period */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/leads/admin/appointments/blocked-periods/${id}`);
    return data;
  },
};

export default adminAppointmentBlockedPeriodsService;
