// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateBlockedPeriodDto {
  /** Start datetime in ISO format */
  startDatetime: string;
  /** End datetime in ISO format */
  endDatetime: string;
  /** Optional label for the blocked period */
  label?: string;
}

export interface UpdateBlockedPeriodDto {
  /** New start datetime (ISO 8601) */
  startDatetime?: string;
  /** New end datetime (ISO 8601) */
  endDatetime?: string;
  /** Label for the blocked period */
  label?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /leads/admin/appointments/blocked-periods — response */
export type ListResponse = unknown;
/** GET /leads/admin/appointments/blocked-periods — query params */
export interface ListParams {
  page?: number;
  limit?: number;
}

/** POST /leads/admin/appointments/blocked-periods — response */
export type CreateResponse = unknown;
/** POST /leads/admin/appointments/blocked-periods — payload */
export type CreateBody = CreateBlockedPeriodDto;

/** PATCH /leads/admin/appointments/blocked-periods/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /leads/admin/appointments/blocked-periods/{id} — payload */
export type UpdateBody = UpdateBlockedPeriodDto;

/** DELETE /leads/admin/appointments/blocked-periods/{id} — response */
export type DeleteResponse = unknown;
