// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateSMSNotificationResponse, CreateSMSNotificationBody, FindSMSNotificationResponse, CreateSMSNotificationEventResponse, CreateSMSNotificationEventBody, FindByIdNotificationSMSNotificationEventResponse, FindByIdSMSNotificationResponse } from './types';

const eventNotificationService = {
  /** Create SMS notification */
  async createSMSNotification(body: CreateSMSNotificationBody): Promise<CreateSMSNotificationResponse> {
    const { data } = await apiClient.post('/api/mailer/sms/create', body);
    return data;
  },

  /** List SMS notifications */
  async findSMSNotification(): Promise<FindSMSNotificationResponse> {
    const { data } = await apiClient.get('/api/mailer/sms');
    return data;
  },

  /** Send SMS via webhook */
  async createSMSNotificationEvent(uuid: string, body: CreateSMSNotificationEventBody): Promise<CreateSMSNotificationEventResponse> {
    const { data } = await apiClient.post(`/api/mailer/sms/webhook/${uuid}`, body);
    return data;
  },

  /** List events by notification */
  async findByIdNotificationSMSNotificationEvent(id_notification: string): Promise<FindByIdNotificationSMSNotificationEventResponse> {
    const { data } = await apiClient.get(`/api/mailer/sms/webhook/${id_notification}`);
    return data;
  },

  /** Get SMS notification by ID */
  async findByIdSMSNotification(id: string): Promise<FindByIdSMSNotificationResponse> {
    const { data } = await apiClient.get(`/api/mailer/sms/${id}`);
    return data;
  },
};

export default eventNotificationService;
