// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateEventNotificationDTO {
  /** SMS notification name */
  name: string;
}

export interface CreateEventNotificationEventDTO {
  /** Message template with dynamic parameters (e.g., Hello {{name}}) */
  message: string;
  /** Destination phone number (international format) */
  destination_number: string;
  /** Sender phone number (international format) */
  sender_number: string;
  /** Parameters to replace in the message template */
  message_params: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /mailer/sms/create — response */
export type CreateSMSNotificationResponse = unknown;
/** POST /mailer/sms/create — payload */
export type CreateSMSNotificationBody = CreateEventNotificationDTO;

/** GET /mailer/sms — response */
export type FindSMSNotificationResponse = unknown;

/** POST /mailer/sms/webhook/{uuid} — response */
export type CreateSMSNotificationEventResponse = unknown;
/** POST /mailer/sms/webhook/{uuid} — payload */
export type CreateSMSNotificationEventBody = CreateEventNotificationEventDTO;

/** GET /mailer/sms/webhook/{id_notification} — response */
export type FindByIdNotificationSMSNotificationEventResponse = unknown;

/** GET /mailer/sms/{id} — response */
export type FindByIdSMSNotificationResponse = unknown;
