// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateCheckoutResponse, CreateCheckoutBody, CancelSubscriptionResponse, ListMySubscriptionsResponse } from './types';

const bcSubscriptionsService = {
  /** Create Stripe checkout session for a product */
  async createCheckout(body: CreateCheckoutBody): Promise<CreateCheckoutResponse> {
    const { data } = await apiClient.post('/api/subscriptions/checkout', body);
    return data;
  },

  /** Cancel subscription at period end */
  async cancelSubscription(id: string): Promise<CancelSubscriptionResponse> {
    const { data } = await apiClient.post(`/api/subscriptions/${id}/cancel`);
    return data;
  },

  /** List my subscriptions */
  async listMySubscriptions(): Promise<ListMySubscriptionsResponse> {
    const { data } = await apiClient.get('/api/subscriptions/my');
    return data;
  },
};

export default bcSubscriptionsService;
