// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateB2CCheckoutSessionDTO {
  /** Product price ID (internal, not Stripe price ID) */
  priceId: string;
  /** Nome do lead (obrigatório se não autenticado) */
  leadName?: string;
  /** Email do lead (obrigatório se não autenticado) */
  leadEmail?: string;
  /** Telefone do lead (obrigatório se não autenticado) */
  leadPhone?: string;
  /** Códigos de cupom a aplicar no checkout. O desconto é calculado sobre o preço base do produto. */
  couponCodes?: string[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /subscriptions/checkout — response */
export type CreateCheckoutResponse = unknown;
/** POST /subscriptions/checkout — payload */
export type CreateCheckoutBody = CreateB2CCheckoutSessionDTO;

/** POST /subscriptions/{id}/cancel — response */
export type CancelSubscriptionResponse = unknown;

/** GET /subscriptions/my — response */
export type ListMySubscriptionsResponse = unknown;
