// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, ListParams, UpsertResponse, UpsertBody, BulkResponse, BulkBody, MaterializeResponse } from './types';

const motordailyinventoryService = {
  async list(tenantId: string, params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/daily-inventory`, { params });
    return data;
  },

  async upsert(tenantId: string, body: UpsertBody): Promise<UpsertResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/daily-inventory`, body);
    return data;
  },

  async bulk(tenantId: string, body: BulkBody): Promise<BulkResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/daily-inventory/bulk`, body);
    return data;
  },

  async materialize(tenantId: string): Promise<MaterializeResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/daily-inventory/materialize`);
    return data;
  },
};

export default motordailyinventoryService;
