// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type UpsertDailyInventoryDto = Record<string, unknown>;

export type BulkDailyInventoryDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/daily-inventory — response */
export type ListResponse = unknown;
/** GET /motor/{tenantId}/daily-inventory — query params */
export interface ListParams {
  room_type_id: string;
  from: string;
  to: string;
}

/** PUT /motor/{tenantId}/daily-inventory — response */
export type UpsertResponse = unknown;
/** PUT /motor/{tenantId}/daily-inventory — payload */
export type UpsertBody = UpsertDailyInventoryDto;

/** POST /motor/{tenantId}/daily-inventory/bulk — response */
export type BulkResponse = unknown;
/** POST /motor/{tenantId}/daily-inventory/bulk — payload */
export type BulkBody = BulkDailyInventoryDto;

/** POST /motor/{tenantId}/daily-inventory/materialize — response */
export type MaterializeResponse = unknown;
