// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ExportContactResponse, EraseContactResponse } from './types';

const adminwhatsappcontactService = {
  async exportContact(tenantId: string, numeroContato: string): Promise<ExportContactResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/whatsapp/contacts/${numeroContato}/export`);
    return data;
  },

  async eraseContact(tenantId: string, numeroContato: string): Promise<EraseContactResponse> {
    const { data } = await apiClient.delete(`/api/admin/hotel-portal/${tenantId}/whatsapp/contacts/${numeroContato}`);
    return data;
  },
};

export default adminwhatsappcontactService;
