// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/whatsapp/contacts/{numeroContato}/export — response */
export type ExportContactResponse = unknown;

/** DELETE /admin/hotel-portal/{tenantId}/whatsapp/contacts/{numeroContato} — response */
export type EraseContactResponse = unknown;
