// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateManualResponse, CreateManualBody, FindByTenantIdResponse, FindByTenantIdParams, GetStatsResponse, GetStatsParams } from './types';

const adminreservationsService = {
  async createManual(tenantId: string, body: CreateManualBody): Promise<CreateManualResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/reservations/${tenantId}`, body);
    return data;
  },

  async findByTenantId(tenantId: string, params: FindByTenantIdParams = {} as FindByTenantIdParams): Promise<FindByTenantIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/reservations/${tenantId}`, { params });
    return data;
  },

  async getStats(tenantId: string, params: GetStatsParams = {} as GetStatsParams): Promise<GetStatsResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/reservations/${tenantId}/stats`, { params });
    return data;
  },
};

export default adminreservationsService;
