// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateReservationDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/reservations/{tenantId} — response */
export type CreateManualResponse = unknown;
/** POST /admin/hotel-portal/reservations/{tenantId} — payload */
export type CreateManualBody = CreateReservationDto;

/** GET /admin/hotel-portal/reservations/{tenantId} — response */
export type FindByTenantIdResponse = unknown;
/** GET /admin/hotel-portal/reservations/{tenantId} — query params */
export interface FindByTenantIdParams {
  source: string;
  status: string;
}

/** GET /admin/hotel-portal/reservations/{tenantId}/stats — response */
export type GetStatsResponse = unknown;
/** GET /admin/hotel-portal/reservations/{tenantId}/stats — query params */
export interface GetStatsParams {
  from: string;
  to: string;
}
