// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetSettingsResponse, UpdateSettingsResponse, UpdateSettingsBody } from './types';

const adminattributionsettingsService = {
  async getSettings(tenantId: string): Promise<GetSettingsResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/attribution-settings`);
    return data;
  },

  async updateSettings(tenantId: string, body: UpdateSettingsBody): Promise<UpdateSettingsResponse> {
    const { data } = await apiClient.put(`/api/admin/hotel-portal/${tenantId}/attribution-settings`, body);
    return data;
  },
};

export default adminattributionsettingsService;
