// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type UpdateAttributionSettingsDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/hotel-portal/{tenantId}/attribution-settings — response */
export type GetSettingsResponse = unknown;

/** PUT /admin/hotel-portal/{tenantId}/attribution-settings — response */
export type UpdateSettingsResponse = unknown;
/** PUT /admin/hotel-portal/{tenantId}/attribution-settings — payload */
export type UpdateSettingsBody = UpdateAttributionSettingsDto;
