// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindByTenantIdResponse, UpdateResponse, UpdateBody, DeleteResponse } from './types';

const adminmilestoneService = {
  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/milestones`, body);
    return data;
  },

  async findByTenantId(tenantId: string): Promise<FindByTenantIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/milestones`);
    return data;
  },

  async update(tenantId: string, id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/admin/hotel-portal/${tenantId}/milestones/${id}`, body);
    return data;
  },

  async delete(tenantId: string, id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/admin/hotel-portal/${tenantId}/milestones/${id}`);
    return data;
  },
};

export default adminmilestoneService;
