// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateMilestoneDto = Record<string, unknown>;

export type UpdateMilestoneDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/milestones — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/milestones — payload */
export type CreateBody = CreateMilestoneDto;

/** GET /admin/hotel-portal/{tenantId}/milestones — response */
export type FindByTenantIdResponse = unknown;

/** PUT /admin/hotel-portal/{tenantId}/milestones/{id} — response */
export type UpdateResponse = unknown;
/** PUT /admin/hotel-portal/{tenantId}/milestones/{id} — payload */
export type UpdateBody = UpdateMilestoneDto;

/** DELETE /admin/hotel-portal/{tenantId}/milestones/{id} — response */
export type DeleteResponse = unknown;
