// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ResolveResponse, ResolveParams, ValidateResponse, ValidateBody } from './types';

const publicCouponsService = {
  /** Resolver cupom pelo código (para pré-carregar no carrinho via link) */
  async resolve(params: ResolveParams = {} as ResolveParams): Promise<ResolveResponse> {
    const { data } = await apiClient.get('/api/public/coupons/resolve', { params });
    return data;
  },

  /** Validar código(s) de cupom contra o carrinho */
  async validate(body: ValidateBody): Promise<ValidateResponse> {
    const { data } = await apiClient.post('/api/public/coupons/validate', body);
    return data;
  },
};

export default publicCouponsService;
