// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface ValidateCouponCartItemDTO {
  productId: string;
  categoryId?: string;
  /** Preço base em centavos (por unidade) */
  basePrice: number;
  quantity: number;
  /** true se o item é uma assinatura recorrente (billing_mode unlimited ou limited) */
  isRecurring?: boolean;
  /** Tipo do item no carrinho. Usado para restringir cupons B2B-only ou B2C-only em carrinhos mistos. */
  itemType?: 'b2b' | 'b2c';
}

export interface ValidateCouponDTO {
  codes: string[];
  cartItems: ValidateCouponCartItemDTO[];
  /** 'b2b' = carrinho puro B2B; 'b2c' = carrinho puro B2C; 'unified' = carrinho misto (eligibilidade determinada pelo itemType de cada item) */
  context: 'b2b' | 'b2c' | 'unified';
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /public/coupons/resolve — response */
export type ResolveResponse = unknown;
/** GET /public/coupons/resolve — query params */
export interface ResolveParams {
  /** Código do cupom (ex: PROMO10) */
  code: string;
}

/** POST /public/coupons/validate — response */
export type ValidateResponse = unknown;
/** POST /public/coupons/validate — payload */
export type ValidateBody = ValidateCouponDTO;
