// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindByClientIdResponse, FindByIdResponse, SubmitForReviewResponse, PublishResponse, PublishBody } from './types';

const reportService = {
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/admin/hotel-portal/reports', body);
    return data;
  },

  async findByClientId(clientId: string): Promise<FindByClientIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/reports/client/${clientId}`);
    return data;
  },

  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/reports/${id}`);
    return data;
  },

  async submitForReview(id: string): Promise<SubmitForReviewResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/reports/${id}/submit-review`);
    return data;
  },

  async publish(id: string, body: PublishBody): Promise<PublishResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/reports/${id}/publish`, body);
    return data;
  },
};

export default reportService;
