// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateReportDto = Record<string, unknown>;

export type PublishReportDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/reports — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/reports — payload */
export type CreateBody = CreateReportDto;

/** GET /admin/hotel-portal/reports/client/{clientId} — response */
export type FindByClientIdResponse = unknown;

/** GET /admin/hotel-portal/reports/{id} — response */
export type FindByIdResponse = unknown;

/** PATCH /admin/hotel-portal/reports/{id}/submit-review — response */
export type SubmitForReviewResponse = unknown;

/** PATCH /admin/hotel-portal/reports/{id}/publish — response */
export type PublishResponse = unknown;
/** PATCH /admin/hotel-portal/reports/{id}/publish — payload */
export type PublishBody = PublishReportDto;
