// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListProductsResponse, CreateProductResponse, CreateProductBody, CalculateCostResponse } from './types';

const adminBcProductsService = {
  /** List all B2C products for the tenant (admin) */
  async listProducts(): Promise<ListProductsResponse> {
    const { data } = await apiClient.get('/api/b2c/products');
    return data;
  },

  /** Create a B2C recurring product (syncs with Stripe) */
  async createProduct(body: CreateProductBody): Promise<CreateProductResponse> {
    const { data } = await apiClient.post('/api/b2c/products', body);
    return data;
  },

  /** Calcular custo total de um produto B2C (admin) */
  async calculateCost(id: string): Promise<CalculateCostResponse> {
    const { data } = await apiClient.post(`/api/b2c/products/${id}/calculate-cost`);
    return data;
  },
};

export default adminBcProductsService;
