// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateB2CProductDTO {
  name: string;
  description?: string;
  /** Unique slug for the product (lowercase letters, numbers, and hyphens only) */
  slug: string;
  /** Product categories for filtering */
  categories?: string[];
  interval: 'month' | 'year' | 'week' | 'quarter';
  /** Interval count (e.g. 3 for quarterly) */
  intervalCount: number;
  /** Price in cents (e.g. 4990 = R$ 49,90) */
  unitAmount: number;
  currency: 'brl' | 'usd' | 'eur' | 'gbp' | 'cad' | 'aud' | 'mxn' | 'ars' | 'cop' | 'clp';
  /** Chip cost (taxa fixa) em centavos adicionada ao preço final (ex: 200 = R$2,00). Padrão: 0 */
  chipCost?: number;
  /** Indica se o produto é físico e requer envio pelos Correios (books, tabs). Padrão: false */
  requiresShipping?: boolean;
}

export interface OrderCostBreakdownResponseDTO {
  /** Preço base em centavos */
  basePrice: number;
  /** Valor do chip cost em centavos (basePrice × chipCostPercent%) */
  chipCostAmount: number;
  /** Frete em centavos (fixo por pedido, 0 para digitais) */
  shippingFee: number;
  /** Total final em centavos */
  total: number;
  currency: string;
  /** Percentual de chip cost aplicado */
  chipCostPercent: number;
  chipCostSource: 'product' | 'category' | 'global' | 'none';
  shippingFeeSource: 'product' | 'category' | 'global' | 'none';
  requiresShipping: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /b2c/products — response */
export type ListProductsResponse = unknown;

/** POST /b2c/products — response */
export type CreateProductResponse = unknown;
/** POST /b2c/products — payload */
export type CreateProductBody = CreateB2CProductDTO;

/** POST /b2c/products/{id}/calculate-cost — response */
export type CalculateCostResponse = OrderCostBreakdownResponseDTO;
