// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { UpsertResponse, UpsertBody, FindByTenantIdResponse, DeleteResponse } from './types';

const adminmetricgoalService = {
  async upsert(tenantId: string, body: UpsertBody): Promise<UpsertResponse> {
    const { data } = await apiClient.put(`/api/admin/hotel-portal/${tenantId}/goals`, body);
    return data;
  },

  async findByTenantId(tenantId: string): Promise<FindByTenantIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/goals`);
    return data;
  },

  async delete(tenantId: string, id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/admin/hotel-portal/${tenantId}/goals/${id}`);
    return data;
  },
};

export default adminmetricgoalService;
