// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type UpsertMetricGoalDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** PUT /admin/hotel-portal/{tenantId}/goals — response */
export type UpsertResponse = unknown;
/** PUT /admin/hotel-portal/{tenantId}/goals — payload */
export type UpsertBody = UpsertMetricGoalDto;

/** GET /admin/hotel-portal/{tenantId}/goals — response */
export type FindByTenantIdResponse = unknown;

/** DELETE /admin/hotel-portal/{tenantId}/goals/{id} — response */
export type DeleteResponse = unknown;
