// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { FindByTenantIdResponse, FindByTenantIdParams, ApproveResponse, RejectResponse, RejectBody } from './types';

const adminbotconfigproposalService = {
  async findByTenantId(tenantId: string, params: FindByTenantIdParams = {} as FindByTenantIdParams): Promise<FindByTenantIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/bot-config-proposals`, { params });
    return data;
  },

  async approve(tenantId: string, id: string): Promise<ApproveResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/bot-config-proposals/${id}/approve`);
    return data;
  },

  async reject(tenantId: string, id: string, body: RejectBody): Promise<RejectResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/bot-config-proposals/${id}/reject`, body);
    return data;
  },
};

export default adminbotconfigproposalService;
