// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type RejectBotConfigProposalDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/hotel-portal/{tenantId}/bot-config-proposals — response */
export type FindByTenantIdResponse = unknown;
/** GET /admin/hotel-portal/{tenantId}/bot-config-proposals — query params */
export interface FindByTenantIdParams {
  status: string;
}

/** PATCH /admin/hotel-portal/{tenantId}/bot-config-proposals/{id}/approve — response */
export type ApproveResponse = unknown;

/** PATCH /admin/hotel-portal/{tenantId}/bot-config-proposals/{id}/reject — response */
export type RejectResponse = unknown;
/** PATCH /admin/hotel-portal/{tenantId}/bot-config-proposals/{id}/reject — payload */
export type RejectBody = RejectBotConfigProposalDto;
