// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface PanelActionResponseDto {
  /** false = acao registrada, mas o bot nao foi avisado agora (sera reenviado). */
  ok: boolean;
  /** Estado do contato devolvido pelo bot (ex.: ATIVO, PAUSADO). */
  state: string | null;
}

export interface RejectBotConfigProposalDto {
  /** Justificativa da rejeicao (obrigatoria). */
  justificativa: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/hotel-portal/{tenantId}/bot-config-proposals — response */
export type FindByTenantIdResponse = unknown;
/** GET /admin/hotel-portal/{tenantId}/bot-config-proposals — query params */
export interface FindByTenantIdParams {
  status: string;
}

/** PATCH /admin/hotel-portal/{tenantId}/bot-config-proposals/{id}/approve — response */
export type ApproveResponse = PanelActionResponseDto;

/** PATCH /admin/hotel-portal/{tenantId}/bot-config-proposals/{id}/reject — response */
export type RejectResponse = unknown;
/** PATCH /admin/hotel-portal/{tenantId}/bot-config-proposals/{id}/reject — payload */
export type RejectBody = RejectBotConfigProposalDto;
