// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { AvailabilityResponse, ListResponse, CreateManualResponse, CreateManualBody, DetailResponse, ImportResponse, ImportBody, RescheduleResponse, RescheduleBody, CancelResponse, CancelBody } from './types';

const motorreservationService = {
  async availability(tenantId: string): Promise<AvailabilityResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/availability`);
    return data;
  },

  async list(tenantId: string): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/reservations`);
    return data;
  },

  async createManual(tenantId: string, body: CreateManualBody): Promise<CreateManualResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/reservations`, body);
    return data;
  },

  async detail(tenantId: string, id: string): Promise<DetailResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/reservations/${id}`);
    return data;
  },

  async import(tenantId: string, body: ImportBody): Promise<ImportResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/reservations/import`, body);
    return data;
  },

  async reschedule(tenantId: string, id: string, body: RescheduleBody): Promise<RescheduleResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/reservations/${id}/reschedule`, body);
    return data;
  },

  async cancel(tenantId: string, id: string, body: CancelBody): Promise<CancelResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/reservations/${id}/cancel`, body);
    return data;
  },
};

export default motorreservationService;
