// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateManualReservationDto = Record<string, unknown>;

export type ImportReservationsDto = Record<string, unknown>;

export type RescheduleDto = Record<string, unknown>;

export type CancelDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/availability — response */
export type AvailabilityResponse = unknown;

/** GET /motor/{tenantId}/reservations — response */
export type ListResponse = unknown;

/** POST /motor/{tenantId}/reservations — response */
export type CreateManualResponse = unknown;
/** POST /motor/{tenantId}/reservations — payload */
export type CreateManualBody = CreateManualReservationDto;

/** GET /motor/{tenantId}/reservations/{id} — response */
export type DetailResponse = unknown;

/** POST /motor/{tenantId}/reservations/import — response */
export type ImportResponse = unknown;
/** POST /motor/{tenantId}/reservations/import — payload */
export type ImportBody = ImportReservationsDto;

/** POST /motor/{tenantId}/reservations/{id}/reschedule — response */
export type RescheduleResponse = unknown;
/** POST /motor/{tenantId}/reservations/{id}/reschedule — payload */
export type RescheduleBody = RescheduleDto;

/** POST /motor/{tenantId}/reservations/{id}/cancel — response */
export type CancelResponse = unknown;
/** POST /motor/{tenantId}/reservations/{id}/cancel — payload */
export type CancelBody = CancelDto;
