// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateProductResponse, CreateProductBody, ListProductsResponse, CreatePaymentLinkResponse, CreatePaymentLinkBody, ListPurchasesResponse, ListPurchasesParams, GetPurchaseResponse, GetMetricsResponse } from './types';

const bbPaymentsService = {
  /** Create a B2B product (syncs with Stripe automatically) */
  async createProduct(body: CreateProductBody): Promise<CreateProductResponse> {
    const { data } = await apiClient.post('/api/b2b/payments/products', body);
    return data;
  },

  /** List all B2B products for the tenant */
  async listProducts(): Promise<ListProductsResponse> {
    const { data } = await apiClient.get('/api/b2b/payments/products');
    return data;
  },

  /** Create a Stripe Checkout payment link for a customer */
  async createPaymentLink(body: CreatePaymentLinkBody): Promise<CreatePaymentLinkResponse> {
    const { data } = await apiClient.post('/api/b2b/payments/create-link', body);
    return data;
  },

  /** List all purchases (checkout funnel) */
  async listPurchases(params: ListPurchasesParams = {} as ListPurchasesParams): Promise<ListPurchasesResponse> {
    const { data } = await apiClient.get('/api/b2b/payments/purchases', { params });
    return data;
  },

  /** Get purchase details */
  async getPurchase(id: string): Promise<GetPurchaseResponse> {
    const { data } = await apiClient.get(`/api/b2b/payments/purchases/${id}`);
    return data;
  },

  /** Get B2B sales funnel metrics */
  async getMetrics(): Promise<GetMetricsResponse> {
    const { data } = await apiClient.get('/api/b2b/payments/metrics');
    return data;
  },
};

export default bbPaymentsService;
