// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateB2BProductDTO {
  name: string;
  description?: string;
  /** Slug único do produto (letras minúsculas, números e hífens) */
  slug: string;
  /** Categorias do produto para filtragem */
  categories?: string[];
  /** Preço em centavos (ex: 4990 = R$49,90) */
  price: number;
  currency: 'brl' | 'usd' | 'eur';
  /** Se o produto é físico e requer envio (books, tabs). Padrão: false */
  requiresShipping?: boolean;
}

export interface CreatePaymentLinkDTO {
  productId: string;
  customerEmail: string;
  customerName?: string;
  customerPhone?: string;
  /** Códigos de cupom (opcionais) */
  couponCodes?: string[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /b2b/payments/products — response */
export type CreateProductResponse = unknown;
/** POST /b2b/payments/products — payload */
export type CreateProductBody = CreateB2BProductDTO;

/** GET /b2b/payments/products — response */
export type ListProductsResponse = unknown;

/** POST /b2b/payments/create-link — response */
export type CreatePaymentLinkResponse = unknown;
/** POST /b2b/payments/create-link — payload */
export type CreatePaymentLinkBody = CreatePaymentLinkDTO;

/** GET /b2b/payments/purchases — response */
export type ListPurchasesResponse = unknown;
/** GET /b2b/payments/purchases — query params */
export interface ListPurchasesParams {
  status?: 'all' | 'pending' | 'completed' | 'abandoned' | 'refunded';
  limit?: number;
  offset?: number;
}

/** GET /b2b/payments/purchases/{id} — response */
export type GetPurchaseResponse = unknown;

/** GET /b2b/payments/metrics — response */
export type GetMetricsResponse = unknown;
