// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreatePlanResponse, CreatePlanBody, FindByTenantIdResponse, FindByIdResponse, AddDeliveryResponse, AddDeliveryBody, UpdateDeliveryResponse, UpdateDeliveryBody } from './types';

const adminsemesterplanService = {
  async createPlan(tenantId: string, body: CreatePlanBody): Promise<CreatePlanResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/semester-plan`, body);
    return data;
  },

  async findByTenantId(tenantId: string): Promise<FindByTenantIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/semester-plan`);
    return data;
  },

  async findById(tenantId: string, planId: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/semester-plan/${planId}`);
    return data;
  },

  async addDelivery(tenantId: string, planId: string, body: AddDeliveryBody): Promise<AddDeliveryResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/semester-plan/${planId}/deliveries`, body);
    return data;
  },

  async updateDelivery(tenantId: string, deliveryId: string, body: UpdateDeliveryBody): Promise<UpdateDeliveryResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/semester-plan/deliveries/${deliveryId}`, body);
    return data;
  },
};

export default adminsemesterplanService;
