// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateSemesterPlanDto = Record<string, unknown>;

export type CreateSemesterPlanDeliveryDto = Record<string, unknown>;

export type UpdateSemesterPlanDeliveryDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/semester-plan — response */
export type CreatePlanResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/semester-plan — payload */
export type CreatePlanBody = CreateSemesterPlanDto;

/** GET /admin/hotel-portal/{tenantId}/semester-plan — response */
export type FindByTenantIdResponse = unknown;

/** GET /admin/hotel-portal/{tenantId}/semester-plan/{planId} — response */
export type FindByIdResponse = unknown;

/** POST /admin/hotel-portal/{tenantId}/semester-plan/{planId}/deliveries — response */
export type AddDeliveryResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/semester-plan/{planId}/deliveries — payload */
export type AddDeliveryBody = CreateSemesterPlanDeliveryDto;

/** PATCH /admin/hotel-portal/{tenantId}/semester-plan/deliveries/{deliveryId} — response */
export type UpdateDeliveryResponse = unknown;
/** PATCH /admin/hotel-portal/{tenantId}/semester-plan/deliveries/{deliveryId} — payload */
export type UpdateDeliveryBody = UpdateSemesterPlanDeliveryDto;
