// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, CreateResponse, CreateBody, UpdateResponse, UpdateBody, RemoveResponse } from './types';

const tenantDomainsService = {
  /** List CORS domains registered for a tenant */
  async list(tenantId: string): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/settings/tenants/${tenantId}/domains`);
    return data;
  },

  /** Register a CORS domain for a tenant */
  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/settings/tenants/${tenantId}/domains`, body);
    return data;
  },

  /** Update (activate/deactivate, set primary) a tenant CORS domain */
  async update(tenantId: string, domainId: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/settings/tenants/${tenantId}/domains/${domainId}`, body);
    return data;
  },

  /** Remove a tenant CORS domain */
  async remove(tenantId: string, domainId: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/settings/tenants/${tenantId}/domains/${domainId}`);
    return data;
  },
};

export default tenantDomainsService;
