// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface TenantDomainResponseDto {
  id: string;
  tenant_id: string;
  type: 'domain' | 'regex';
  value: string;
  is_primary: boolean;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateTenantDomainDto {
  /** "domain" auto-scopes to the host and its subdomains (https only). "regex" is matched against Origin verbatim. */
  type?: 'domain' | 'regex';
  /** Bare host for type=domain, or a regex source (must compile) for type=regex */
  value: string;
  /** Demotes any other primary row for the same tenant */
  is_primary?: boolean;
}

export interface UpdateTenantDomainDto {
  active?: boolean;
  /** Setting true demotes any other primary row for the same tenant */
  is_primary?: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /settings/tenants/{tenantId}/domains — response */
export type ListResponse = TenantDomainResponseDto[];

/** POST /settings/tenants/{tenantId}/domains — response */
export type CreateResponse = TenantDomainResponseDto;
/** POST /settings/tenants/{tenantId}/domains — payload */
export type CreateBody = CreateTenantDomainDto;

/** PATCH /settings/tenants/{tenantId}/domains/{domainId} — response */
export type UpdateResponse = TenantDomainResponseDto;
/** PATCH /settings/tenants/{tenantId}/domains/{domainId} — payload */
export type UpdateBody = UpdateTenantDomainDto;

/** DELETE /settings/tenants/{tenantId}/domains/{domainId} — response */
export type RemoveResponse = unknown;
