// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateLeadResponse, CreateLeadBody, FindLeadsResponse, FindLeadsParams, FindLeadByIdResponse, UpdateLeadResponse, UpdateLeadBody, DeleteLeadResponse, GetLeadAttachmentsResponse, AddAttachmentResponse, AddAttachmentBody, RemoveAttachmentResponse, UpdateLeadStatusResponse } from './types';

const leadsService = {
  /** Create lead with optional attachments */
  async createLead(body: CreateLeadBody): Promise<CreateLeadResponse> {
    const { data } = await apiClient.post('/api/leads', body);
    return data;
  },

  /** List leads */
  async findLeads(params: FindLeadsParams = {} as FindLeadsParams): Promise<FindLeadsResponse> {
    const { data } = await apiClient.get('/api/leads', { params });
    return data;
  },

  /** Get lead by ID */
  async findLeadById(id: string): Promise<FindLeadByIdResponse> {
    const { data } = await apiClient.get(`/api/leads/${id}`);
    return data;
  },

  /** Update lead */
  async updateLead(id: string, body: UpdateLeadBody): Promise<UpdateLeadResponse> {
    const { data } = await apiClient.patch(`/api/leads/${id}`, body);
    return data;
  },

  /** Delete lead */
  async deleteLead(id: string): Promise<DeleteLeadResponse> {
    const { data } = await apiClient.delete(`/api/leads/${id}`);
    return data;
  },

  /** List lead attachments */
  async getLeadAttachments(id: string): Promise<GetLeadAttachmentsResponse> {
    const { data } = await apiClient.get(`/api/leads/${id}/attachments`);
    return data;
  },

  /** Add attachment to lead */
  async addAttachment(id: string, body: AddAttachmentBody): Promise<AddAttachmentResponse> {
    const { data } = await apiClient.post(`/api/leads/${id}/attachments`, body);
    return data;
  },

  /** Remove attachment from lead */
  async removeAttachment(id: string, attachmentId: string): Promise<RemoveAttachmentResponse> {
    const { data } = await apiClient.delete(`/api/leads/${id}/attachments/${attachmentId}`);
    return data;
  },

  /** Update lead status */
  async updateLeadStatus(id: string): Promise<UpdateLeadStatusResponse> {
    const { data } = await apiClient.put(`/api/leads/${id}/status`);
    return data;
  },
};

export default leadsService;
