// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface AttachmentDto {
  /** Media asset ID */
  asset_id: string;
  /** Attachment label */
  label?: string;
}

export interface CreateLeadWithAttachmentsDto {
  /** Lead name */
  name?: string;
  /** Lead email */
  email?: string;
  /** Lead phone number */
  phone_number?: string;
  /** Lead origin */
  origin: 1 | 2 | 3 | 4 | 5 | 6;
  /** Origin source */
  origin_font?: string;
  /** Description */
  description?: string;
  /** Collection ID (CUID) */
  collection_id?: string;
  /** Additional data */
  data?: Record<string, unknown>;
  /** File attachments */
  attachments?: AttachmentDto[];
}

export interface UpdateLeadDto {
  /** Lead name */
  name?: string;
  /** Lead email address */
  email?: string;
  /** Lead phone number */
  phone_number?: string;
  /** Lead origin */
  origin?: 1 | 2 | 3 | 4 | 5 | 6;
  /** Lead origin source */
  origin_font?: string;
  /** Description or notes about the lead */
  description?: string;
  /** Additional lead data in JSON format */
  data?: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /leads — response */
export type CreateLeadResponse = unknown;
/** POST /leads — payload */
export type CreateLeadBody = CreateLeadWithAttachmentsDto;

/** GET /leads — response */
export type FindLeadsResponse = unknown;
/** GET /leads — query params */
export interface FindLeadsParams {
  /** Page number */
  page?: string;
  /** Items per page */
  limit?: string;
}

/** GET /leads/{id} — response */
export type FindLeadByIdResponse = unknown;

/** PATCH /leads/{id} — response */
export type UpdateLeadResponse = unknown;
/** PATCH /leads/{id} — payload */
export type UpdateLeadBody = UpdateLeadDto;

/** DELETE /leads/{id} — response */
export type DeleteLeadResponse = unknown;

/** GET /leads/{id}/attachments — response */
export type GetLeadAttachmentsResponse = unknown;

/** POST /leads/{id}/attachments — response */
export type AddAttachmentResponse = unknown;
/** POST /leads/{id}/attachments — payload */
export type AddAttachmentBody = AttachmentDto;

/** DELETE /leads/{id}/attachments/{attachmentId} — response */
export type RemoveAttachmentResponse = unknown;

/** PUT /leads/{id}/status — response */
export type UpdateLeadStatusResponse = unknown;
