// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListProductsResponse, GetProductResponse, CalculateCostResponse, CalculateCostBody, GetProductContentResponse } from './types';

const bcProductsService = {
  /** Listar produtos ativos com preços */
  async listProducts(): Promise<ListProductsResponse> {
    const { data } = await apiClient.get('/api/products');
    return data;
  },

  /** Buscar produto por slug */
  async getProduct(slug: string): Promise<GetProductResponse> {
    const { data } = await apiClient.get(`/api/products/${slug}`);
    return data;
  },

  /** Calcular custo total do pedido */
  async calculateCost(id: string, body: CalculateCostBody): Promise<CalculateCostResponse> {
    const { data } = await apiClient.post(`/api/products/${id}/calculate-cost`, body);
    return data;
  },

  /** Acessar conteúdo do produto (requer acesso ativo) */
  async getProductContent(slug: string): Promise<GetProductContentResponse> {
    const { data } = await apiClient.get(`/api/products/${slug}/content`);
    return data;
  },
};

export default bcProductsService;
