// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CalculateCostBodyDTO = Record<string, unknown>;

export interface OrderCostBreakdownResponseDTO {
  /** Preço base em centavos */
  basePrice: number;
  /** Valor do chip cost em centavos (basePrice × chipCostPercent%) */
  chipCostAmount: number;
  /** Frete em centavos (fixo por pedido, 0 para digitais) */
  shippingFee: number;
  /** Total final em centavos */
  total: number;
  currency: string;
  /** Percentual de chip cost aplicado */
  chipCostPercent: number;
  chipCostSource: 'product' | 'category' | 'global' | 'none';
  shippingFeeSource: 'product' | 'category' | 'global' | 'none';
  requiresShipping: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /products — response */
export type ListProductsResponse = unknown;

/** GET /products/{slug} — response */
export type GetProductResponse = unknown;

/** POST /products/{id}/calculate-cost — response */
export type CalculateCostResponse = OrderCostBreakdownResponseDTO;
/** POST /products/{id}/calculate-cost — payload */
export type CalculateCostBody = CalculateCostBodyDTO;

/** GET /products/{slug}/content — response */
export type GetProductContentResponse = unknown;
