// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateTemplateResponse, CreateTemplateBody, FindTemplatesResponse, SendMessageResponse, SendMessageBody, GetMessageHistoryResponse, GetMessageHistoryParams } from './types';

const whatsappService = {
  async createTemplate(clientId: string, body: CreateTemplateBody): Promise<CreateTemplateResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/whatsapp/${clientId}/templates`, body);
    return data;
  },

  async findTemplates(clientId: string): Promise<FindTemplatesResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/whatsapp/${clientId}/templates`);
    return data;
  },

  async sendMessage(clientId: string, body: SendMessageBody): Promise<SendMessageResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/whatsapp/${clientId}/send`, body);
    return data;
  },

  async getMessageHistory(clientId: string, params: GetMessageHistoryParams = {} as GetMessageHistoryParams): Promise<GetMessageHistoryResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/whatsapp/${clientId}/messages`, { params });
    return data;
  },
};

export default whatsappService;
