// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateWhatsAppTemplateDto = Record<string, unknown>;

export type SendWhatsAppMessageDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/whatsapp/{clientId}/templates — response */
export type CreateTemplateResponse = unknown;
/** POST /admin/hotel-portal/whatsapp/{clientId}/templates — payload */
export type CreateTemplateBody = CreateWhatsAppTemplateDto;

/** GET /admin/hotel-portal/whatsapp/{clientId}/templates — response */
export type FindTemplatesResponse = unknown;

/** POST /admin/hotel-portal/whatsapp/{clientId}/send — response */
export type SendMessageResponse = unknown;
/** POST /admin/hotel-portal/whatsapp/{clientId}/send — payload */
export type SendMessageBody = SendWhatsAppMessageDto;

/** GET /admin/hotel-portal/whatsapp/{clientId}/messages — response */
export type GetMessageHistoryResponse = unknown;
/** GET /admin/hotel-portal/whatsapp/{clientId}/messages — query params */
export interface GetMessageHistoryParams {
  page: string;
  limit: string;
}
