// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, ListParams, GetOneResponse, CancelResponse, CompleteResponse } from './types';

const adminAppointmentsService = {
  /** List appointments */
  async list(params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/leads/admin/appointments', { params });
    return data;
  },

  /** Get appointment details */
  async getOne(id: string): Promise<GetOneResponse> {
    const { data } = await apiClient.get(`/api/leads/admin/appointments/${id}`);
    return data;
  },

  /** Cancel an appointment */
  async cancel(id: string): Promise<CancelResponse> {
    const { data } = await apiClient.patch(`/api/leads/admin/appointments/${id}/cancel`);
    return data;
  },

  /** Mark appointment as completed */
  async complete(id: string): Promise<CompleteResponse> {
    const { data } = await apiClient.patch(`/api/leads/admin/appointments/${id}/complete`);
    return data;
  },
};

export default adminAppointmentsService;
