// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /leads/admin/appointments — response */
export type ListResponse = unknown;
/** GET /leads/admin/appointments — query params */
export interface ListParams {
  /** Page number */
  page?: number;
  /** Items per page */
  limit?: number;
  /** Filter by appointment status */
  status?: 'confirmed' | 'cancelled' | 'completed';
}

/** GET /leads/admin/appointments/{id} — response */
export type GetOneResponse = unknown;

/** PATCH /leads/admin/appointments/{id}/cancel — response */
export type CancelResponse = unknown;

/** PATCH /leads/admin/appointments/{id}/complete — response */
export type CompleteResponse = unknown;
