// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ExportReportResponse, ExportReportParams } from './types';

const pdfexportService = {
  async exportReport(clientId: string, params: ExportReportParams = {} as ExportReportParams): Promise<ExportReportResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/export/report`, { params });
    return data;
  },
};

export default pdfexportService;
