// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /hotel-portal/{clientId}/export/report — response */
export type ExportReportResponse = unknown;
/** GET /hotel-portal/{clientId}/export/report — query params */
export interface ExportReportParams {
  from: string;
  to: string;
  section: string;
}
