// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ReceiveResponse } from './types';

const pmsbookingwebhookService = {
  async receive(clientId: string): Promise<ReceiveResponse> {
    const { data } = await apiClient.post(`/api/webhooks/booking/${clientId}`);
    return data;
  },
};

export default pmsbookingwebhookService;
