// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ReceiveResponse, ReceiveBody } from './types';

const pmsbookingwebhookService = {
  async receive(clientId: string, body: ReceiveBody): Promise<ReceiveResponse> {
    const { data } = await apiClient.post(`/api/webhooks/booking/${clientId}`, body);
    return data;
  },
};

export default pmsbookingwebhookService;
