// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /webhooks/booking/{clientId} — response */
export type ReceiveResponse = unknown;
