// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface PmsBookingWebhookDto {
  /** Id da reserva no PMS (idempotencia por tenant). */
  externalId: string;
  /** Motor/PMS de origem. */
  engine?: string;
  /** Status da reserva no PMS. */
  status: 'confirmed' | 'modified' | 'cancelled';
  /** Canal: direct ou ota:<booking|expedia|airbnb|tripadvisor>. */
  channel?: string;
  /** Valor total em centavos. */
  amount?: number;
  /** Check-in (YYYY-MM-DD). */
  checkIn: string;
  /** Check-out (YYYY-MM-DD). */
  checkOut: string;
  /** Quando a reserva foi feita (ISO 8601). */
  bookedAt?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /webhooks/booking/{clientId} — response */
export type ReceiveResponse = unknown;
/** POST /webhooks/booking/{clientId} — payload */
export type ReceiveBody = PmsBookingWebhookDto;
