// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { HandleStripeWebhookResponse } from './types';

const bbWebhooksService = {
  /** Stripe webhook endpoint for B2B one-time payments */
  async handleStripeWebhook(): Promise<HandleStripeWebhookResponse> {
    const { data } = await apiClient.post('/api/webhooks/b2b/stripe');
    return data;
  },
};

export default bbWebhooksService;
