// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /webhooks/b2b/stripe — response */
export type HandleStripeWebhookResponse = unknown;
