// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListProductsResponse, GetProductResponse, CalculateCostResponse } from './types';

const publicBcProductsService = {
  /** Listar produtos B2C ativos (público) */
  async listProducts(): Promise<ListProductsResponse> {
    const { data } = await apiClient.get('/api/public/b2c/products');
    return data;
  },

  /** Buscar produto B2C por slug (público) */
  async getProduct(slug: string): Promise<GetProductResponse> {
    const { data } = await apiClient.get(`/api/public/b2c/products/${slug}`);
    return data;
  },

  /** Calcular custo total de um produto B2C (público) */
  async calculateCost(id: string): Promise<CalculateCostResponse> {
    const { data } = await apiClient.post(`/api/public/b2c/products/${id}/calculate-cost`);
    return data;
  },
};

export default publicBcProductsService;
