// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, FindByIdResponse, UpdateResponse, UpdateBody, DeactivateResponse, InsertOtaDataResponse, InsertOtaDataBody, GetOtaDataResponse, GetOtaDataParams } from './types';

const adminhotelclientService = {
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/admin/hotel-portal/clients', body);
    return data;
  },

  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/admin/hotel-portal/clients');
    return data;
  },

  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/clients/${id}`);
    return data;
  },

  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/clients/${id}`, body);
    return data;
  },

  async deactivate(id: string): Promise<DeactivateResponse> {
    const { data } = await apiClient.delete(`/api/admin/hotel-portal/clients/${id}`);
    return data;
  },

  async insertOtaData(id: string, body: InsertOtaDataBody): Promise<InsertOtaDataResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/clients/${id}/ota-data`, body);
    return data;
  },

  async getOtaData(id: string, params: GetOtaDataParams = {} as GetOtaDataParams): Promise<GetOtaDataResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/clients/${id}/ota-data`, { params });
    return data;
  },
};

export default adminhotelclientService;
