// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateClientDto = Record<string, unknown>;

export type UpdateClientDto = Record<string, unknown>;

export type InsertOtaDataDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/clients — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/clients — payload */
export type CreateBody = CreateClientDto;

/** GET /admin/hotel-portal/clients — response */
export type FindAllResponse = unknown;

/** GET /admin/hotel-portal/clients/{id} — response */
export type FindByIdResponse = unknown;

/** PATCH /admin/hotel-portal/clients/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /admin/hotel-portal/clients/{id} — payload */
export type UpdateBody = UpdateClientDto;

/** DELETE /admin/hotel-portal/clients/{id} — response */
export type DeactivateResponse = unknown;

/** POST /admin/hotel-portal/clients/{id}/ota-data — response */
export type InsertOtaDataResponse = unknown;
/** POST /admin/hotel-portal/clients/{id}/ota-data — payload */
export type InsertOtaDataBody = InsertOtaDataDto;

/** GET /admin/hotel-portal/clients/{id}/ota-data — response */
export type GetOtaDataResponse = unknown;
/** GET /admin/hotel-portal/clients/{id}/ota-data — query params */
export interface GetOtaDataParams {
  from: string;
  to: string;
}
