// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, FindAllParams, GetAllTenantLeadsResponse, GetAllTenantLeadsParams, FindOneResponse, UpdateResponse, UpdateBody, RemoveResponse, RegenerateSecretKeyResponse, GetCollectionLeadsResponse, GetCollectionLeadsParams } from './types';

const leadCollectionsService = {
  /** Create a new lead collection */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/leads/collections', body);
    return data;
  },

  /** List all collections for the tenant */
  async findAll(params: FindAllParams = {} as FindAllParams): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/leads/collections', { params });
    return data;
  },

  /** List all leads across all tenant collections */
  async getAllTenantLeads(params: GetAllTenantLeadsParams = {} as GetAllTenantLeadsParams): Promise<GetAllTenantLeadsResponse> {
    const { data } = await apiClient.get('/api/leads/collections/leads', { params });
    return data;
  },

  /** Get a collection by ID */
  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/leads/collections/${id}`);
    return data;
  },

  /** Update a collection */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/leads/collections/${id}`, body);
    return data;
  },

  /** Deactivate a collection */
  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/leads/collections/${id}`);
    return data;
  },

  /** Regenerate collection secret key */
  async regenerateSecretKey(id: string): Promise<RegenerateSecretKeyResponse> {
    const { data } = await apiClient.post(`/api/leads/collections/${id}/regenerate-key`);
    return data;
  },

  /** List leads within a specific collection */
  async getCollectionLeads(id: string, params: GetCollectionLeadsParams = {} as GetCollectionLeadsParams): Promise<GetCollectionLeadsResponse> {
    const { data } = await apiClient.get(`/api/leads/collections/${id}/leads`, { params });
    return data;
  },
};

export default leadCollectionsService;
