// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateCollectionDto {
  /** Name of the lead collection */
  name: string;
  /** Internal source identifier */
  source: string;
}

export interface UpdateCollectionDto {
  /** Name of the lead collection */
  name?: string;
  /** Internal source identifier */
  source?: string;
  /** Whether the collection is active */
  active?: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /leads/collections — response */
export type CreateResponse = unknown;
/** POST /leads/collections — payload */
export type CreateBody = CreateCollectionDto;

/** GET /leads/collections — response */
export type FindAllResponse = unknown;
/** GET /leads/collections — query params */
export interface FindAllParams {
  page?: number;
  limit?: number;
  active?: boolean;
}

/** GET /leads/collections/leads — response */
export type GetAllTenantLeadsResponse = unknown;
/** GET /leads/collections/leads — query params */
export interface GetAllTenantLeadsParams {
  page: number;
  limit: number;
}

/** GET /leads/collections/{id} — response */
export type FindOneResponse = unknown;

/** PUT /leads/collections/{id} — response */
export type UpdateResponse = unknown;
/** PUT /leads/collections/{id} — payload */
export type UpdateBody = UpdateCollectionDto;

/** DELETE /leads/collections/{id} — response */
export type RemoveResponse = unknown;

/** POST /leads/collections/{id}/regenerate-key — response */
export type RegenerateSecretKeyResponse = unknown;

/** GET /leads/collections/{id}/leads — response */
export type GetCollectionLeadsResponse = unknown;
/** GET /leads/collections/{id}/leads — query params */
export interface GetCollectionLeadsParams {
  page: number;
  limit: number;
}
