// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetOwnResponse, UpdateOwnResponse, UpdateOwnBody, GetForTenantResponse, UpdateForTenantResponse, UpdateForTenantBody } from './types';

const notificationSettingsService = {
  /** Get own tenant notification settings */
  async getOwn(): Promise<GetOwnResponse> {
    const { data } = await apiClient.get('/api/notifications/settings');
    return data;
  },

  /** Update own tenant notification settings */
  async updateOwn(body: UpdateOwnBody): Promise<UpdateOwnResponse> {
    const { data } = await apiClient.patch('/api/notifications/settings', body);
    return data;
  },

  /** Get any tenant notification settings (super_admin) */
  async getForTenant(tenantId: string): Promise<GetForTenantResponse> {
    const { data } = await apiClient.get(`/api/notifications/settings/${tenantId}`);
    return data;
  },

  /** Update any tenant notification settings (super_admin) */
  async updateForTenant(tenantId: string, body: UpdateForTenantBody): Promise<UpdateForTenantResponse> {
    const { data } = await apiClient.patch(`/api/notifications/settings/${tenantId}`, body);
    return data;
  },
};

export default notificationSettingsService;
