// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UpdateNotificationSettingsDTO {
  email_enabled?: boolean;
  inapp_enabled?: boolean;
  event_settings?: Record<string, unknown>;
  cron_settings?: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /notifications/settings — response */
export type GetOwnResponse = unknown;

/** PATCH /notifications/settings — response */
export type UpdateOwnResponse = unknown;
/** PATCH /notifications/settings — payload */
export type UpdateOwnBody = UpdateNotificationSettingsDTO;

/** GET /notifications/settings/{tenantId} — response */
export type GetForTenantResponse = unknown;

/** PATCH /notifications/settings/{tenantId} — response */
export type UpdateForTenantResponse = unknown;
/** PATCH /notifications/settings/{tenantId} — payload */
export type UpdateForTenantBody = UpdateNotificationSettingsDTO;
