// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface NotificationSettingsResponseDto {
  id: string;
  tenant_id: string;
  email_enabled: boolean;
  inapp_enabled: boolean;
  event_settings: Record<string, boolean>;
  cron_settings: Record<string, boolean>;
  timezone: string;
  created_at: string;
  updated_at: string;
}

export interface UpdateNotificationSettingsDTO {
  email_enabled?: boolean;
  inapp_enabled?: boolean;
  event_settings?: Record<string, unknown>;
  cron_settings?: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /notifications/settings — response */
export type GetOwnResponse = NotificationSettingsResponseDto;

/** PATCH /notifications/settings — response */
export type UpdateOwnResponse = NotificationSettingsResponseDto;
/** PATCH /notifications/settings — payload */
export type UpdateOwnBody = UpdateNotificationSettingsDTO;

/** GET /notifications/settings/{tenantId} — response */
export type GetForTenantResponse = NotificationSettingsResponseDto;

/** PATCH /notifications/settings/{tenantId} — response */
export type UpdateForTenantResponse = NotificationSettingsResponseDto;
/** PATCH /notifications/settings/{tenantId} — payload */
export type UpdateForTenantBody = UpdateNotificationSettingsDTO;
