// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, ListResponse, FindByIdResponse, UpdateResponse, UpdateBody, DeleteResponse, PublishResponse } from './types';

const admincontentpostService = {
  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/content-posts`, body);
    return data;
  },

  async list(tenantId: string): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/content-posts`);
    return data;
  },

  async findById(tenantId: string, id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/${tenantId}/content-posts/${id}`);
    return data;
  },

  async update(tenantId: string, id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/content-posts/${id}`, body);
    return data;
  },

  async delete(tenantId: string, id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/admin/hotel-portal/${tenantId}/content-posts/${id}`);
    return data;
  },

  async publish(tenantId: string, id: string): Promise<PublishResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/content-posts/${id}/publish`);
    return data;
  },
};

export default admincontentpostService;
