// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateContentPostDto = Record<string, unknown>;

export type UpdateContentPostDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/content-posts — response */
export type CreateResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/content-posts — payload */
export type CreateBody = CreateContentPostDto;

/** GET /admin/hotel-portal/{tenantId}/content-posts — response */
export type ListResponse = unknown;

/** GET /admin/hotel-portal/{tenantId}/content-posts/{id} — response */
export type FindByIdResponse = unknown;

/** PATCH /admin/hotel-portal/{tenantId}/content-posts/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /admin/hotel-portal/{tenantId}/content-posts/{id} — payload */
export type UpdateBody = UpdateContentPostDto;

/** DELETE /admin/hotel-portal/{tenantId}/content-posts/{id} — response */
export type DeleteResponse = unknown;

/** PATCH /admin/hotel-portal/{tenantId}/content-posts/{id}/publish — response */
export type PublishResponse = unknown;
