// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { FindAllResponse, FindAllParams, FindByIdResponse, UpdateResponse, UpdateBody, DeleteResponse, DeactivateResponse } from './types';

const adminUserManagementService = {
  /** List all users with pagination */
  async findAll(params: FindAllParams = {} as FindAllParams): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/admin/users', { params });
    return data;
  },

  /** Get user by CUID */
  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/users/${id}`);
    return data;
  },

  /** Update user data by CUID (super_admin only) */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/admin/users/${id}`, body);
    return data;
  },

  /** Delete user permanently by CUID (super_admin only) */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/admin/users/${id}`);
    return data;
  },

  /** Deactivate user by CUID (super_admin only) */
  async deactivate(id: string): Promise<DeactivateResponse> {
    const { data } = await apiClient.patch(`/api/admin/users/${id}/deactivate`);
    return data;
  },
};

export default adminUserManagementService;
