// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UserListItemDTO {
  /** User CUID (25-character identifier) */
  id: string;
  name: string;
  email: string;
  phone_number: string;
  cpf: string;
  /** Plan CUID (25-character identifier) */
  plan_id: string;
  date_expires_in: string | null;
  created_at: string;
}

export interface UserListResponseDTO {
  users: UserListItemDTO[];
  pagination: Record<string, unknown>;
}

export interface UserResponseDTO {
  /** User CUID (25-character identifier) */
  id: string;
  name: string;
  email: string;
  phone_number: string;
  cpf: string;
  sex: number | null;
  date_of_birth: string | null;
  date_expires_in: string | null;
  /** Plan CUID (25-character identifier) */
  plan_id: string;
  created_at: string;
  updated_at: string;
}

export interface UpdateUserDTO {
  /** User name */
  name?: string;
  /** User email */
  email?: string;
  /** User phone number */
  phone_number?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /admin/users — response */
export type FindAllResponse = UserListResponseDTO;
/** GET /admin/users — query params */
export interface FindAllParams {
  page?: number;
  limit?: number;
}

/** GET /admin/users/{id} — response */
export type FindByIdResponse = UserResponseDTO;

/** PATCH /admin/users/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /admin/users/{id} — payload */
export type UpdateBody = UpdateUserDTO;

/** DELETE /admin/users/{id} — response */
export type DeleteResponse = unknown;

/** PATCH /admin/users/{id}/deactivate — response */
export type DeactivateResponse = unknown;
