// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateRoomTypeDto = Record<string, unknown>;

export type UpdateRoomTypeDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/room-types — response */
export type ListResponse = unknown;

/** POST /motor/{tenantId}/room-types — response */
export type CreateResponse = unknown;
/** POST /motor/{tenantId}/room-types — payload */
export type CreateBody = CreateRoomTypeDto;

/** PUT /motor/{tenantId}/room-types/{id} — response */
export type UpdateResponse = unknown;
/** PUT /motor/{tenantId}/room-types/{id} — payload */
export type UpdateBody = UpdateRoomTypeDto;
