// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, ListAssetsResponse, ListAssetsParams, UploadAssetResponse, UploadAssetBody, ReplaceResponse, ReplaceBody, UpdateResponse, UpdateBody, DeleteResponse, RegenerateKeyResponse } from './types';

const cmsBlogsService = {
  /** Create a new blog in the current tenant */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/cms/blogs', body);
    return data;
  },

  /** List all blogs in the current tenant */
  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/cms/blogs');
    return data;
  },

  /** List assets available for articles of a blog */
  async listAssets(blogId: string, params: ListAssetsParams = {} as ListAssetsParams): Promise<ListAssetsResponse> {
    const { data } = await apiClient.get(`/api/cms/blogs/${blogId}/assets`, { params });
    return data;
  },

  /** Upload an asset to the blog media collection */
  async uploadAsset(blogId: string, body: UploadAssetBody): Promise<UploadAssetResponse> {
    const { data } = await apiClient.post(`/api/cms/blogs/${blogId}/assets`, body);
    return data;
  },

  /** Replace blog metadata */
  async replace(blogId: string, body: ReplaceBody): Promise<ReplaceResponse> {
    const { data } = await apiClient.put(`/api/cms/blogs/${blogId}`, body);
    return data;
  },

  /** Partially update blog metadata */
  async update(blogId: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/cms/blogs/${blogId}`, body);
    return data;
  },

  /** Delete a blog (and cascade delete articles) */
  async delete(blogId: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/cms/blogs/${blogId}`);
    return data;
  },

  /** Regenerate blog secret key */
  async regenerateKey(blogId: string): Promise<RegenerateKeyResponse> {
    const { data } = await apiClient.post(`/api/cms/blogs/${blogId}/regenerate-key`);
    return data;
  },
};

export default cmsBlogsService;
