// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateBlogDTO {
  /** Blog name */
  name: string;
  /** Blog description */
  description?: string;
  /** Media collection ID used by this blog for article uploads */
  mediaCollectionId: string;
}

export interface UpdateBlogDTO {
  /** Blog name */
  name?: string;
  /** Blog description */
  description?: string;
  /** Media collection ID used by this blog for article uploads */
  mediaCollectionId?: string;
  /** Whether the blog is active and can be consumed by the public API */
  active?: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/blogs — response */
export type CreateResponse = unknown;
/** POST /cms/blogs — payload */
export type CreateBody = CreateBlogDTO;

/** GET /cms/blogs — response */
export type FindAllResponse = unknown;

/** GET /cms/blogs/{blogId}/assets — response */
export type ListAssetsResponse = unknown;
/** GET /cms/blogs/{blogId}/assets — query params */
export interface ListAssetsParams {
  status?: 'processing' | 'ready' | 'failed' | 'archived';
  mime_type?: string;
  page?: number;
  limit?: number;
}

/** POST /cms/blogs/{blogId}/assets — response */
export type UploadAssetResponse = unknown;
/** POST /cms/blogs/{blogId}/assets — payload */
export interface UploadAssetBody {
  /** File to upload (max 50MB). Supported formats depend on blog media collection configuration. */
  file: string;
  /** Alternative text for accessibility (recommended for images) */
  alt_text?: string;
  /** Additional metadata as JSON (optional). Can include custom fields for categorization. */
  metadata?: Record<string, unknown>;
}

/** PUT /cms/blogs/{blogId} — response */
export type ReplaceResponse = unknown;
/** PUT /cms/blogs/{blogId} — payload */
export type ReplaceBody = UpdateBlogDTO;

/** PATCH /cms/blogs/{blogId} — response */
export type UpdateResponse = unknown;
/** PATCH /cms/blogs/{blogId} — payload */
export type UpdateBody = UpdateBlogDTO;

/** DELETE /cms/blogs/{blogId} — response */
export type DeleteResponse = unknown;

/** POST /cms/blogs/{blogId}/regenerate-key — response */
export type RegenerateKeyResponse = unknown;
