// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetGlobalConfigResponse, UpsertGlobalConfigResponse, UpsertGlobalConfigBody, GetProductsByCategoryResponse, UpdateProductFeesResponse, UpdateProductFeesBody, CalculateCostResponse } from './types';

const bbFeesService = {
  /** Buscar taxa global B2B (one-time) */
  async getGlobalConfig(): Promise<GetGlobalConfigResponse> {
    const { data } = await apiClient.get('/api/b2b/fees/global');
    return data;
  },

  /** Criar ou atualizar taxa global B2B (one-time) */
  async upsertGlobalConfig(body: UpsertGlobalConfigBody): Promise<UpsertGlobalConfigResponse> {
    const { data } = await apiClient.put('/api/b2b/fees/global', body);
    return data;
  },

  /** Listar produtos B2B de uma categoria */
  async getProductsByCategory(categoryId: string): Promise<GetProductsByCategoryResponse> {
    const { data } = await apiClient.get(`/api/b2b/fees/categories/${categoryId}/products`);
    return data;
  },

  /** Configurar taxas de um produto B2B específico */
  async updateProductFees(productId: string, body: UpdateProductFeesBody): Promise<UpdateProductFeesResponse> {
    const { data } = await apiClient.patch(`/api/b2b/fees/products/${productId}`, body);
    return data;
  },

  /** Calcular custo total de um produto B2B */
  async calculateCost(productId: string): Promise<CalculateCostResponse> {
    const { data } = await apiClient.post(`/api/b2b/fees/products/${productId}/calculate-cost`);
    return data;
  },
};

export default bbFeesService;
