// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UpsertFeeConfigDTO {
  /** Chip cost percentual global (ex: 2.5 = 2.5% sobre o preço do produto). Aplicado a todos os produtos sem override. */
  chipCostPercent: number;
  /** Frete fixo global em centavos (ex: 1500 = R$15,00). Aplicado a produtos físicos sem override. */
  shippingFee: number;
}

export interface UpdateProductFeesDTO {
  /** ID da categoria do produto. null = sem categoria (usa taxa global). */
  categoryId?: string | null;
  /** Override de chip cost % para este produto específico. null = remove override (herda da categoria/global). */
  chipCostOverride?: number | null;
  /** Override de frete em centavos para este produto. null = remove override. */
  shippingFeeOverride?: number | null;
  /** Se o produto é físico e requer envio (books, tabs). */
  requiresShipping?: boolean;
}

export interface OrderCostBreakdownResponseDTO {
  /** Preço base em centavos */
  basePrice: number;
  /** Valor do chip cost em centavos (basePrice × chipCostPercent%) */
  chipCostAmount: number;
  /** Frete em centavos (fixo por pedido, 0 para digitais) */
  shippingFee: number;
  /** Total final em centavos */
  total: number;
  currency: string;
  /** Percentual de chip cost aplicado */
  chipCostPercent: number;
  chipCostSource: 'product' | 'category' | 'global' | 'none';
  shippingFeeSource: 'product' | 'category' | 'global' | 'none';
  requiresShipping: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /b2b/fees/global — response */
export type GetGlobalConfigResponse = unknown;

/** PUT /b2b/fees/global — response */
export type UpsertGlobalConfigResponse = unknown;
/** PUT /b2b/fees/global — payload */
export type UpsertGlobalConfigBody = UpsertFeeConfigDTO;

/** GET /b2b/fees/categories/{categoryId}/products — response */
export type GetProductsByCategoryResponse = unknown;

/** PATCH /b2b/fees/products/{productId} — response */
export type UpdateProductFeesResponse = unknown;
/** PATCH /b2b/fees/products/{productId} — payload */
export type UpdateProductFeesBody = UpdateProductFeesDTO;

/** POST /b2b/fees/products/{productId}/calculate-cost — response */
export type CalculateCostResponse = OrderCostBreakdownResponseDTO;
