// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CalculateCostResponse, CalculateCostBody, CheckoutResponse, CheckoutBody } from './types';

const publicUnifiedCheckoutService = {
  /** Calcular custo de carrinho misto B2B + B2C (público) */
  async calculateCost(body: CalculateCostBody): Promise<CalculateCostResponse> {
    const { data } = await apiClient.post('/api/public/checkout/calculate-cost', body);
    return data;
  },

  /** Checkout unificado B2B + B2C (público) */
  async checkout(body: CheckoutBody): Promise<CheckoutResponse> {
    const { data } = await apiClient.post('/api/public/checkout', body);
    return data;
  },
};

export default publicUnifiedCheckoutService;
