// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UnifiedCartItemDTO {
  /** ID do produto */
  productId: string;
  /** Tipo do produto */
  type: 'b2b' | 'b2c';
  /** ID do preço B2C (obrigatório para type=b2c) */
  priceId?: string;
  /** Quantidade */
  quantity: number;
}

export interface UnifiedCalculateCostDTO {
  items: UnifiedCartItemDTO[];
}

export type UnifiedCartCostResponseDTO = Record<string, unknown>;

export interface UnifiedCheckoutDTO {
  items: UnifiedCartItemDTO[];
  leadName?: string;
  leadEmail?: string;
  leadPhone?: string;
  /** Códigos de cupom (opcionais). Aplicados sobre os itens elegíveis do carrinho. */
  couponCodes?: string[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /public/checkout/calculate-cost — response */
export type CalculateCostResponse = UnifiedCartCostResponseDTO;
/** POST /public/checkout/calculate-cost — payload */
export type CalculateCostBody = UnifiedCalculateCostDTO;

/** POST /public/checkout — response */
export type CheckoutResponse = unknown;
/** POST /public/checkout — payload */
export type CheckoutBody = UnifiedCheckoutDTO;
