// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { HandleStripeWebhookResponse } from './types';

const bcWebhooksService = {
  /** Stripe webhook endpoint for B2C subscriptions */
  async handleStripeWebhook(): Promise<HandleStripeWebhookResponse> {
    const { data } = await apiClient.post('/api/webhooks/b2c/stripe');
    return data;
  },
};

export default bcWebhooksService;
