// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetResponse, CreateResponse, CreateBody, UpdateResponse, UpdateBody, DeleteResponse } from './types';

const paymentsBillingConfigService = {
  /** Get billing config for the current tenant */
  async get(): Promise<GetResponse> {
    const { data } = await apiClient.get('/api/payments/billing-config');
    return data;
  },

  /** Create billing config for the current tenant */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/payments/billing-config', body);
    return data;
  },

  /** Update billing config for the current tenant */
  async update(body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch('/api/payments/billing-config', body);
    return data;
  },

  /** Delete billing config for the current tenant */
  async delete(): Promise<DeleteResponse> {
    const { data } = await apiClient.delete('/api/payments/billing-config');
    return data;
  },
};

export default paymentsBillingConfigService;
