// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface TenantBillingConfigResponseDTO {
  id: string;
  tenantId: string;
  /** Stripe publishable key (safe to expose to frontend) */
  stripePublishableKey: string | null;
  /** Whether a Stripe secret key is configured (value is never returned) */
  hasStripeSecretKey: boolean;
  /** Whether a Stripe webhook secret is configured (value is never returned) */
  hasStripeWebhookSecret: boolean;
  /** Stripe Price IDs per interval */
  stripePriceIds: Record<string, unknown> | null;
  billingInterval: 'monthly' | 'quarterly' | 'semiannual' | 'annual';
  billingCollectionMode: 'upfront' | 'installments';
  trialEnabled: boolean;
  trialDays: number;
  currency: string;
  planName: string | null;
  planDescription: string | null;
  metadata: Record<string, unknown> | null;
  active: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface CreateTenantBillingConfigDTO {
  /** Stripe publishable key for this tenant (pk_live_... or pk_test_...) */
  stripePublishableKey?: string;
  /** Stripe secret key for this tenant (sk_live_... or sk_test_...). Stored encrypted. */
  stripeSecretKey?: string;
  /** Stripe webhook signing secret (whsec_...). Stored encrypted. */
  stripeWebhookSecret?: string;
  /** Map of billing interval → Stripe Price ID. Allows different prices per period. */
  stripePriceIds?: Record<string, unknown>;
  /** Default billing interval for this tenant */
  billingInterval: 'monthly' | 'quarterly' | 'semiannual' | 'annual';
  /** How the billing is collected. "upfront" = full period charged at once. "installments" = monthly installments with discount. */
  billingCollectionMode: 'upfront' | 'installments';
  /** Enable trial period */
  trialEnabled?: boolean;
  /** Trial duration in days */
  trialDays?: number;
  /** Currency code (ISO 4217) */
  currency?: string;
  /** Plan display name */
  planName?: string;
  /** Plan description shown in the panel */
  planDescription?: string;
  /** Arbitrary metadata for panel rendering (feature flags, UI hints, etc.) */
  metadata?: Record<string, unknown>;
}

export interface UpdateTenantBillingConfigDTO {
  stripePublishableKey?: string;
  stripeSecretKey?: string;
  stripeWebhookSecret?: string;
  stripePriceIds?: Record<string, unknown>;
  billingInterval?: 'monthly' | 'quarterly' | 'semiannual' | 'annual';
  billingCollectionMode?: 'upfront' | 'installments';
  trialEnabled?: boolean;
  trialDays?: number;
  currency?: string;
  planName?: string;
  planDescription?: string;
  metadata?: Record<string, unknown>;
  active?: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /payments/billing-config — response */
export type GetResponse = TenantBillingConfigResponseDTO;

/** POST /payments/billing-config — response */
export type CreateResponse = TenantBillingConfigResponseDTO;
/** POST /payments/billing-config — payload */
export type CreateBody = CreateTenantBillingConfigDTO;

/** PATCH /payments/billing-config — response */
export type UpdateResponse = TenantBillingConfigResponseDTO;
/** PATCH /payments/billing-config — payload */
export type UpdateBody = UpdateTenantBillingConfigDTO;

/** DELETE /payments/billing-config — response */
export type DeleteResponse = unknown;
