// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateEmailCampaignResponse, CreateEmailCampaignBody, GetAllEmailCampaignsResponse, GetAllEmailCampaignsParams, GetEmailCampaignByIdResponse, UpdateCopyVariantResponse, UpdateCopyVariantBody, UpdateCampaignBatchSizeResponse, UpdateCampaignBatchSizeBody, CloseSetupResponse, PauseCampaignResponse, ResumeCampaignResponse } from './types';

const emailCampaignService = {
  /** Create email campaign */
  async createEmailCampaign(body: CreateEmailCampaignBody): Promise<CreateEmailCampaignResponse> {
    const { data } = await apiClient.post('/api/mailer', body);
    return data;
  },

  /** List campaigns */
  async getAllEmailCampaigns(params: GetAllEmailCampaignsParams = {} as GetAllEmailCampaignsParams): Promise<GetAllEmailCampaignsResponse> {
    const { data } = await apiClient.get('/api/mailer', { params });
    return data;
  },

  /** Get campaign by ID */
  async getEmailCampaignById(id: string): Promise<GetEmailCampaignByIdResponse> {
    const { data } = await apiClient.get(`/api/mailer/${id}`);
    return data;
  },

  /** Update copy variation type */
  async updateCopyVariant(id: string, body: UpdateCopyVariantBody): Promise<UpdateCopyVariantResponse> {
    const { data } = await apiClient.put(`/api/mailer/${id}/copy-variant`, body);
    return data;
  },

  /** Update batch size */
  async updateCampaignBatchSize(id: string, body: UpdateCampaignBatchSizeBody): Promise<UpdateCampaignBatchSizeResponse> {
    const { data } = await apiClient.put(`/api/mailer/${id}/batch-size`, body);
    return data;
  },

  /** Close campaign setup */
  async closeSetup(id: string): Promise<CloseSetupResponse> {
    const { data } = await apiClient.post(`/api/mailer/${id}/close-setup`);
    return data;
  },

  /** Pause campaign */
  async pauseCampaign(id: string): Promise<PauseCampaignResponse> {
    const { data } = await apiClient.post(`/api/mailer/${id}/pause`);
    return data;
  },

  /** Resume campaign */
  async resumeCampaign(id: string): Promise<ResumeCampaignResponse> {
    const { data } = await apiClient.post(`/api/mailer/${id}/resume`);
    return data;
  },
};

export default emailCampaignService;
