// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateEmailCampaignDto {
  /** Email campaign name */
  name: string;
}

export interface UpdateCopyVariantDto {
  /** Copy variation type */
  copy_variation_type: 1 | 2;
}

export interface UpdateCampaignBatchSizeDto {
  /** Campaign batch size (minimum 100) */
  campaign_batch_size: number;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /mailer — response */
export type CreateEmailCampaignResponse = unknown;
/** POST /mailer — payload */
export type CreateEmailCampaignBody = CreateEmailCampaignDto;

/** GET /mailer — response */
export type GetAllEmailCampaignsResponse = unknown;
/** GET /mailer — query params */
export interface GetAllEmailCampaignsParams {
  /** Page number */
  page?: string;
  /** Items per page */
  limit?: string;
}

/** GET /mailer/{id} — response */
export type GetEmailCampaignByIdResponse = unknown;

/** PUT /mailer/{id}/copy-variant — response */
export type UpdateCopyVariantResponse = unknown;
/** PUT /mailer/{id}/copy-variant — payload */
export type UpdateCopyVariantBody = UpdateCopyVariantDto;

/** PUT /mailer/{id}/batch-size — response */
export type UpdateCampaignBatchSizeResponse = unknown;
/** PUT /mailer/{id}/batch-size — payload */
export type UpdateCampaignBatchSizeBody = UpdateCampaignBatchSizeDto;

/** POST /mailer/{id}/close-setup — response */
export type CloseSetupResponse = unknown;

/** POST /mailer/{id}/pause — response */
export type PauseCampaignResponse = unknown;

/** POST /mailer/{id}/resume — response */
export type ResumeCampaignResponse = unknown;
