// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GenerateFXImageResponse, GenerateFXImageBody } from './types';

const adminPostService = {
  /** Generate an ImageFX image from a prompt */
  async generateFXImage(body: GenerateFXImageBody): Promise<GenerateFXImageResponse> {
    const { data } = await apiClient.post('/api/admin/post/generate-image/image-fx', body);
    return data;
  },
};

export default adminPostService;
