// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/post/generate-image/image-fx — response */
export type GenerateFXImageResponse = unknown;
/** POST /admin/post/generate-image/image-fx — payload */
export interface GenerateFXImageBody {
  prompt: string;
}
