// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListArticlesResponse, ListArticlesParams, GetArticleBySlugResponse } from './types';

const cmsPublicApiService = {
  /** List published articles for a blog */
  async listArticles(params: ListArticlesParams = {} as ListArticlesParams): Promise<ListArticlesResponse> {
    const { data } = await apiClient.get('/api/cms/public/articles', { params });
    return data;
  },

  /** Retrieve a single published article by slug */
  async getArticleBySlug(slug: string): Promise<GetArticleBySlugResponse> {
    const { data } = await apiClient.get(`/api/cms/public/articles/${slug}`);
    return data;
  },
};

export default cmsPublicApiService;
