// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /cms/public/articles — response */
export interface ListArticlesResponse {
  data?: {
    id?: string;
    title?: string;
    language?: string;
    meta_title?: string;
    meta_description?: string | null;
    focus_keyword?: string | null;
    slug?: string;
    content?: string;
    published_at?: string;
    cover_image?: {
      id?: string;
      url?: string;
      alt_text?: string | null;
    } | null;
    author?: {
      id?: string;
      first_name?: string;
      last_name?: string;
      full_name?: string;
      biography?: string | null;
      avatar?: {
        id?: string;
        url?: string;
        alt_text?: string | null;
      } | null;
    } | null;
  }[];
  meta?: {
    page?: number;
    limit?: number;
    total?: number;
    total_pages?: number;
  };
}
/** GET /cms/public/articles — query params */
export interface ListArticlesParams {
  /** Page number for pagination */
  page?: number;
  /** Articles per page (max: 50) */
  limit?: number;
}

/** GET /cms/public/articles/{slug} — response */
export interface GetArticleBySlugResponse {
  id?: string;
  title?: string;
  language?: string;
  meta_title?: string;
  meta_description?: string | null;
  focus_keyword?: string | null;
  slug?: string;
  content?: string;
  status?: 'published';
  published_at?: string;
  created_at?: string;
  updated_at?: string;
  cover_image?: {
    id?: string;
    url?: string;
    alt_text?: string | null;
  } | null;
  author?: {
    id?: string;
    first_name?: string;
    last_name?: string;
    full_name?: string;
    biography?: string | null;
    avatar?: {
      id?: string;
      url?: string;
      alt_text?: string | null;
    } | null;
  } | null;
}
