// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { AttachResponse, AttachBody, DetachResponse, DetachBody, GetEntityAssetsResponse, GetEntityAssetsParams, ReorderResponse, ReorderBody } from './types';

const cmsMediaRelationsService = {
  /** Attach a media asset to an entity */
  async attach(body: AttachBody): Promise<AttachResponse> {
    const { data } = await apiClient.post('/api/cms/relations/attach', body);
    return data;
  },

  /** Detach a media asset from an entity */
  async detach(body: DetachBody): Promise<DetachResponse> {
    const { data } = await apiClient.post('/api/cms/relations/detach', body);
    return data;
  },

  /** Get all assets attached to an entity */
  async getEntityAssets(entityType: string, entityId: string, params: GetEntityAssetsParams = {} as GetEntityAssetsParams): Promise<GetEntityAssetsResponse> {
    const { data } = await apiClient.get(`/api/cms/relations/${entityType}/${entityId}`, { params });
    return data;
  },

  /** Reorder assets for an entity */
  async reorder(body: ReorderBody): Promise<ReorderResponse> {
    const { data } = await apiClient.put('/api/cms/relations/reorder', body);
    return data;
  },
};

export default cmsMediaRelationsService;
