// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface AttachMediaDTO {
  /** Media asset ID to attach (UUID string) */
  asset_id: string;
  /** Entity type (e.g., article, brand, company, user) */
  entity_type: string;
  /** Entity ID (UUID string or integer as string) */
  entity_id: string;
  /** Entity ID type discriminator (uuid for Article/Author, int for others) */
  entity_id_type: 'uuid' | 'int';
  /** Relation type (e.g., featured, gallery, avatar, logo) */
  relation_type: string;
  /** Display order for sorting (auto-assigned if not provided) */
  display_order?: number;
  /** Additional metadata for the relation */
  metadata?: Record<string, unknown>;
}

export interface DetachMediaDTO {
  /** Media asset ID to detach (UUID string) */
  asset_id: string;
  /** Entity type (e.g., article, brand, company, user) */
  entity_type: string;
  /** Entity ID (UUID string or integer as string) */
  entity_id: string;
  /** Relation type (e.g., featured, gallery, avatar, logo) */
  relation_type: string;
}

export interface ReorderItem {
  /** Relation ID (UUID string) */
  relation_id: string;
  /** New display order */
  display_order: number;
}

export interface ReorderMediaDTO {
  /** Array of relation IDs with new display orders */
  items: ReorderItem[];
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/relations/attach — response */
export type AttachResponse = unknown;
/** POST /cms/relations/attach — payload */
export type AttachBody = AttachMediaDTO;

/** POST /cms/relations/detach — response */
export type DetachResponse = unknown;
/** POST /cms/relations/detach — payload */
export type DetachBody = DetachMediaDTO;

/** GET /cms/relations/{entityType}/{entityId} — response */
export type GetEntityAssetsResponse = unknown;
/** GET /cms/relations/{entityType}/{entityId} — query params */
export interface GetEntityAssetsParams {
  /** Filter by relation type (e.g., featured, gallery) */
  relation_type?: string;
}

/** PUT /cms/relations/reorder — response */
export type ReorderResponse = unknown;
/** PUT /cms/relations/reorder — payload */
export type ReorderBody = ReorderMediaDTO;
