// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { RedirectResponse } from './types';

const whatsappredirectService = {
  async redirect(code: string): Promise<RedirectResponse> {
    const { data } = await apiClient.get(`/api/wa/${code}`);
    return data;
  },
};

export default whatsappredirectService;
