// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /wa/{code} — response */
export type RedirectResponse = unknown;
