// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { RangeResponse, RangeParams, GradeResponse, GradeParams, MonthResponse, MonthParams } from './types';

const motorcalendarService = {
  async range(tenantId: string, params: RangeParams = {} as RangeParams): Promise<RangeResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/calendar/range`, { params });
    return data;
  },

  async grade(tenantId: string, params: GradeParams = {} as GradeParams): Promise<GradeResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/calendar/grade`, { params });
    return data;
  },

  async month(tenantId: string, params: MonthParams = {} as MonthParams): Promise<MonthResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/calendar`, { params });
    return data;
  },
};

export default motorcalendarService;
