// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/calendar/range — response */
export type RangeResponse = unknown;
/** GET /motor/{tenantId}/calendar/range — query params */
export interface RangeParams {
  from: string;
  to: string;
}

/** GET /motor/{tenantId}/calendar/grade — response */
export type GradeResponse = unknown;
/** GET /motor/{tenantId}/calendar/grade — query params */
export interface GradeParams {
  from: string;
  to: string;
}

/** GET /motor/{tenantId}/calendar — response */
export type MonthResponse = unknown;
/** GET /motor/{tenantId}/calendar — query params */
export interface MonthParams {
  mes: string;
}
