// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetResponse } from './types';

const tenantModulesService = {
  /** Enabled modules for the current tenant */
  async get(): Promise<GetResponse> {
    const { data } = await apiClient.get('/api/settings/modules');
    return data;
  },
};

export default tenantModulesService;
