// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /settings/modules — response */
export type GetResponse = Record<string, boolean>;
