// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetDashboardResponse, GetDashboardParams, GetDashboardByTenantResponse, GetDashboardByTenantParams, GetGlobalDashboardResponse, GetGlobalDashboardParams, ListAvailableIntegrationsResponse, GetModuleMetricsResponse, GetModuleMetricsParams, GetTimeSeriesResponse, GetTimeSeriesParams } from './types';

const statsDashboardService = {
  /** Get stats dashboard */
  async getDashboard(params: GetDashboardParams = {} as GetDashboardParams): Promise<GetDashboardResponse> {
    const { data } = await apiClient.get('/api/stats/dashboard', { params });
    return data;
  },

  /** Get stats dashboard for a tenant */
  async getDashboardByTenant(tenantId: string, params: GetDashboardByTenantParams = {} as GetDashboardByTenantParams): Promise<GetDashboardByTenantResponse> {
    const { data } = await apiClient.get(`/api/stats/dashboard/tenants/${tenantId}`, { params });
    return data;
  },

  /** Get aggregated dashboard across all tenants */
  async getGlobalDashboard(params: GetGlobalDashboardParams = {} as GetGlobalDashboardParams): Promise<GetGlobalDashboardResponse> {
    const { data } = await apiClient.get('/api/stats/dashboard/global', { params });
    return data;
  },

  /** List available external integrations */
  async listAvailableIntegrations(): Promise<ListAvailableIntegrationsResponse> {
    const { data } = await apiClient.get('/api/stats/available-integrations');
    return data;
  },

  /** Get metrics for a single module */
  async getModuleMetrics(moduleKey: string, params: GetModuleMetricsParams = {} as GetModuleMetricsParams): Promise<GetModuleMetricsResponse> {
    const { data } = await apiClient.get(`/api/stats/module/${moduleKey}`, { params });
    return data;
  },

  /** Get time-series data */
  async getTimeSeries(params: GetTimeSeriesParams = {} as GetTimeSeriesParams): Promise<GetTimeSeriesResponse> {
    const { data } = await apiClient.get('/api/stats/timeseries', { params });
    return data;
  },
};

export default statsDashboardService;
