// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface MetricValueResponseDto {
  key: string;
  label: string;
  value: Record<string, unknown>;
  unit?: string;
  /** Percentage change vs previous period */
  trend?: number;
  metadata?: Record<string, unknown>;
}

export interface MetricGroupResponseDto {
  moduleKey: string;
  label: string;
  description?: string;
  metrics: MetricValueResponseDto[];
  fetchedAt: string;
  /** Error message if this provider failed */
  error?: string;
}

export interface DashboardResponseDto {
  groups: MetricGroupResponseDto[];
  generatedAt: string;
}

export interface AvailableIntegrationDto {
  key: string;
  label: string;
  description: string;
  /** Required and optional config fields with descriptions */
  configSchema: Record<string, unknown>;
}

export interface TimeSeriesPointDto {
  /** Date in YYYY-MM-DD format */
  date: string;
  value: number;
}

export interface TimeSeriesGroupResponseDto {
  moduleKey: string;
  label: string;
  metricKey: string;
  metricLabel: string;
  granularity: 'day' | 'week' | 'month';
  series: TimeSeriesPointDto[];
  from: string;
  to: string;
}

export interface TimeSeriesResponseDto {
  series: TimeSeriesGroupResponseDto[];
  generatedAt: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /stats/dashboard — response */
export type GetDashboardResponse = DashboardResponseDto;
/** GET /stats/dashboard — query params */
export interface GetDashboardParams {
  /** Start date (ISO 8601). Defaults to 30 days ago. */
  from?: string;
  /** End date (ISO 8601). Defaults to today. */
  to?: string;
}

/** GET /stats/dashboard/tenants/{tenantId} — response */
export type GetDashboardByTenantResponse = DashboardResponseDto;
/** GET /stats/dashboard/tenants/{tenantId} — query params */
export interface GetDashboardByTenantParams {
  /** Start date (ISO 8601). Defaults to 30 days ago. */
  from?: string;
  /** End date (ISO 8601). Defaults to today. */
  to?: string;
}

/** GET /stats/dashboard/global — response */
export type GetGlobalDashboardResponse = DashboardResponseDto;
/** GET /stats/dashboard/global — query params */
export interface GetGlobalDashboardParams {
  /** Start date (ISO 8601). Defaults to 30 days ago. */
  from?: string;
  /** End date (ISO 8601). Defaults to today. */
  to?: string;
}

/** GET /stats/available-integrations — response */
export type ListAvailableIntegrationsResponse = AvailableIntegrationDto[];

/** GET /stats/module/{moduleKey} — response */
export type GetModuleMetricsResponse = MetricGroupResponseDto;
/** GET /stats/module/{moduleKey} — query params */
export interface GetModuleMetricsParams {
  /** Start date (ISO 8601). Defaults to 30 days ago. */
  from?: string;
  /** End date (ISO 8601). Defaults to today. */
  to?: string;
}

/** GET /stats/timeseries — response */
export type GetTimeSeriesResponse = TimeSeriesResponseDto;
/** GET /stats/timeseries — query params */
export interface GetTimeSeriesParams {
  /** Start date (ISO 8601). Defaults to 30 days ago. */
  from?: string;
  /** End date (ISO 8601). Defaults to today. */
  to?: string;
  /** Time granularity for grouping data points. */
  granularity?: 'day' | 'week' | 'month';
  module: string;
}
