// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { SubmitResponse, SubmitBody, UpdateResponse } from './types';

const publicLeadSubmissionService = {
  /** Submit a lead */
  async submit(body: SubmitBody): Promise<SubmitResponse> {
    const { data } = await apiClient.post('/api/leads/submit', body);
    return data;
  },

  /** Update an existing lead */
  async update(leadId: string): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/leads/${leadId}`);
    return data;
  },
};

export default publicLeadSubmissionService;
