// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface SubmitLeadDto {
  /** Lead name */
  name: string;
  /** Lead email address */
  email: string;
  /** Lead phone number */
  phone?: string;
  /** Lead message or inquiry */
  message?: string;
  /** Lead source identifier */
  source?: string;
  /** Additional lead data in JSON format */
  data?: Record<string, unknown>;
  /** Client IP address */
  ipAddress?: string;
  /** Client user agent */
  userAgent?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /leads/submit — response */
export interface SubmitResponse {
  data?: {
    leadId?: string;
  };
  status?: number;
}
/** POST /leads/submit — payload */
export type SubmitBody = SubmitLeadDto;

/** PATCH /leads/{leadId} — response */
export type UpdateResponse = unknown;
