// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, CreateResponse, CreateBody, ListProvidersResponse, GetByIdResponse, UpdateResponse, UpdateBody, DeleteResponse } from './types';

const statsIntegrationsService = {
  /** List tenant integrations */
  async list(): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/stats/integrations');
    return data;
  },

  /** Create integration */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/stats/integrations', body);
    return data;
  },

  /** List available providers */
  async listProviders(): Promise<ListProvidersResponse> {
    const { data } = await apiClient.get('/api/stats/integrations/providers');
    return data;
  },

  /** Get integration by ID */
  async getById(id: string): Promise<GetByIdResponse> {
    const { data } = await apiClient.get(`/api/stats/integrations/${id}`);
    return data;
  },

  /** Update integration */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/stats/integrations/${id}`, body);
    return data;
  },

  /** Delete integration */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/stats/integrations/${id}`);
    return data;
  },
};

export default statsIntegrationsService;
