// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface StatsIntegrationResponseDto {
  id: string;
  tenant_id: string;
  key: string;
  label: string;
  /** Config with secret fields masked */
  config: Record<string, unknown>;
  active: boolean;
  created_at: string;
  updated_at: string;
}

export interface CreateStatsIntegrationDto {
  /** Integration key matching a registered IExternalMetricProvider */
  key: string;
  /** Human-readable label for this integration instance */
  label: string;
  /** Provider-specific configuration (API keys, site URLs, etc.) */
  config: Record<string, unknown>;
}

export interface AvailableIntegrationDto {
  key: string;
  label: string;
  description: string;
  /** Required and optional config fields with descriptions */
  configSchema: Record<string, unknown>;
}

export interface UpdateStatsIntegrationDto {
  label?: string;
  config?: Record<string, unknown>;
  active?: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /stats/integrations — response */
export type ListResponse = StatsIntegrationResponseDto[];

/** POST /stats/integrations — response */
export type CreateResponse = StatsIntegrationResponseDto;
/** POST /stats/integrations — payload */
export type CreateBody = CreateStatsIntegrationDto;

/** GET /stats/integrations/providers — response */
export type ListProvidersResponse = AvailableIntegrationDto[];

/** GET /stats/integrations/{id} — response */
export type GetByIdResponse = StatsIntegrationResponseDto;

/** PATCH /stats/integrations/{id} — response */
export type UpdateResponse = StatsIntegrationResponseDto;
/** PATCH /stats/integrations/{id} — payload */
export type UpdateBody = UpdateStatsIntegrationDto;

/** DELETE /stats/integrations/{id} — response */
export type DeleteResponse = unknown;
