// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { HandleResponse } from './types';

const bedswebhookService = {
  async handle(tenantId: string): Promise<HandleResponse> {
    const { data } = await apiClient.post(`/api/webhooks/beds24/${tenantId}`);
    return data;
  },
};

export default bedswebhookService;
