// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /webhooks/beds24/{tenantId} — response */
export type HandleResponse = unknown;
