// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ListResponse, ListParams, CreateResponse, CreateBody, UpdateResponse, UpdateBody } from './types';

const motorunitService = {
  async list(tenantId: string, params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/units`, { params });
    return data;
  },

  async create(tenantId: string, body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/units`, body);
    return data;
  },

  async update(tenantId: string, id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/units/${id}`, body);
    return data;
  },
};

export default motorunitService;
