// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateUnitDto = Record<string, unknown>;

export type UpdateUnitDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/units — response */
export type ListResponse = unknown;
/** GET /motor/{tenantId}/units — query params */
export interface ListParams {
  room_type_id: string;
}

/** POST /motor/{tenantId}/units — response */
export type CreateResponse = unknown;
/** POST /motor/{tenantId}/units — payload */
export type CreateBody = CreateUnitDto;

/** PUT /motor/{tenantId}/units/{id} — response */
export type UpdateResponse = unknown;
/** PUT /motor/{tenantId}/units/{id} — payload */
export type UpdateBody = UpdateUnitDto;
