// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, FindMyTenantsResponse, FindByIdResponse, UpdateResponse, UpdateBody, DeleteResponse, DeleteBody, AssignAdminResponse, AssignAdminBody, UnassignAdminResponse, FindAdminsByTenantResponse, DeactivateResponse, ActivateResponse, RestoreResponse, DeletionStatusResponse, UpdateAdminRoleResponse, UpdateAdminRoleBody } from './types';

const tenantManagementService = {
  /** Create a new tenant (super_admin only) */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/tenants', body);
    return data;
  },

  /** List all tenants (super_admin only) */
  async findAll(): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/tenants');
    return data;
  },

  /** List tenants the authenticated admin belongs to */
  async findMyTenants(): Promise<FindMyTenantsResponse> {
    const { data } = await apiClient.get('/api/tenants/my-tenants');
    return data;
  },

  /** Get tenant by ID (super_admin only) */
  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/tenants/${id}`);
    return data;
  },

  /** Update tenant (super_admin only) */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/tenants/${id}`, body);
    return data;
  },

  /** Schedule tenant deletion (super_admin only) */
  async delete(id: string, body: DeleteBody): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/tenants/${id}`, { data: body });
    return data;
  },

  /** Assign admin to tenant (super_admin only) */
  async assignAdmin(body: AssignAdminBody): Promise<AssignAdminResponse> {
    const { data } = await apiClient.post('/api/tenants/assign', body);
    return data;
  },

  /** Remove admin from tenant (super_admin only) */
  async unassignAdmin(tenantId: string, adminId: string): Promise<UnassignAdminResponse> {
    const { data } = await apiClient.delete(`/api/tenants/${tenantId}/admins/${adminId}`);
    return data;
  },

  /** List admins of a tenant (super_admin only) */
  async findAdminsByTenant(tenantId: string): Promise<FindAdminsByTenantResponse> {
    const { data } = await apiClient.get(`/api/tenants/${tenantId}/admins`);
    return data;
  },

  /** Deactivate tenant (super_admin only) */
  async deactivate(id: string): Promise<DeactivateResponse> {
    const { data } = await apiClient.patch(`/api/tenants/${id}/deactivate`);
    return data;
  },

  /** Activate tenant (super_admin only) */
  async activate(id: string): Promise<ActivateResponse> {
    const { data } = await apiClient.patch(`/api/tenants/${id}/activate`);
    return data;
  },

  /** Restore tenant scheduled for deletion (super_admin only) */
  async restore(id: string): Promise<RestoreResponse> {
    const { data } = await apiClient.post(`/api/tenants/${id}/restore`);
    return data;
  },

  /** Get tenant deletion status (super_admin only) */
  async deletionStatus(id: string): Promise<DeletionStatusResponse> {
    const { data } = await apiClient.get(`/api/tenants/${id}/deletion-status`);
    return data;
  },

  /** Update admin role in tenant (super_admin only) */
  async updateAdminRole(tenantId: string, adminId: string, body: UpdateAdminRoleBody): Promise<UpdateAdminRoleResponse> {
    const { data } = await apiClient.patch(`/api/tenants/${tenantId}/admins/${adminId}/role`, body);
    return data;
  },
};

export default tenantManagementService;
