// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateTenantDTO {
  /** Tenant company name */
  name: string;
  /** Unique URL-friendly slug */
  slug: string;
  /** Tenant custom domain */
  domain?: string;
}

export interface TenantResponseDTO {
  /** Tenant CUID (25-character identifier) */
  id: string;
  name: string;
  slug: string;
  domain: string | null;
  active: boolean;
  archived_at?: string | null;
  deletion_requested_at?: string | null;
  deletion_scheduled_for_at?: string | null;
  deletion_requested_by?: string | null;
  deletion_reason?: string | null;
  /** IANA timezone string */
  timezone?: string;
  created_at: string;
  updated_at: string;
}

export interface TenantWithAdminsDTO {
  /** Tenant CUID (25-character identifier) */
  id: string;
  name: string;
  slug: string;
  domain: string | null;
  active: boolean;
  archived_at?: string | null;
  deletion_requested_at?: string | null;
  deletion_scheduled_for_at?: string | null;
  deletion_requested_by?: string | null;
  deletion_reason?: string | null;
  /** IANA timezone string */
  timezone?: string;
  created_at: string;
  updated_at: string;
  AdminTenant: Record<string, unknown>[];
}

export interface UpdateTenantDTO {
  /** Tenant company name */
  name?: string;
  /** Unique URL-friendly slug */
  slug?: string;
  /** Tenant custom domain */
  domain?: string;
  /** IANA timezone string */
  timezone?: string;
}

export interface ScheduleTenantDeletionDTO {
  /** Optional reason for scheduling tenant deletion */
  reason?: string;
}

export interface AssignAdminToTenantDTO {
  /** Admin CUID to assign */
  admin_id: string;
  /** Tenant CUID to assign to */
  tenant_id: string;
}

export interface TenantDeletionStatusDTO {
  /** Tenant CUID (25-character identifier) */
  id: string;
  active: boolean;
  scheduled_for_deletion: boolean;
  archived_at?: string | null;
  deletion_requested_at?: string | null;
  deletion_scheduled_for_at?: string | null;
  deletion_requested_by?: string | null;
  deletion_reason?: string | null;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /tenants — response */
export type CreateResponse = TenantResponseDTO;
/** POST /tenants — payload */
export type CreateBody = CreateTenantDTO;

/** GET /tenants — response */
export type FindAllResponse = TenantWithAdminsDTO[];

/** GET /tenants/my-tenants — response */
export type FindMyTenantsResponse = TenantResponseDTO[];

/** GET /tenants/{id} — response */
export type FindByIdResponse = TenantWithAdminsDTO;

/** PATCH /tenants/{id} — response */
export type UpdateResponse = TenantResponseDTO;
/** PATCH /tenants/{id} — payload */
export type UpdateBody = UpdateTenantDTO;

/** DELETE /tenants/{id} — response */
export type DeleteResponse = unknown;
/** DELETE /tenants/{id} — payload */
export type DeleteBody = ScheduleTenantDeletionDTO;

/** POST /tenants/assign — response */
export type AssignAdminResponse = unknown;
/** POST /tenants/assign — payload */
export type AssignAdminBody = AssignAdminToTenantDTO;

/** DELETE /tenants/{tenantId}/admins/{adminId} — response */
export type UnassignAdminResponse = unknown;

/** GET /tenants/{tenantId}/admins — response */
export type FindAdminsByTenantResponse = unknown;

/** PATCH /tenants/{id}/deactivate — response */
export type DeactivateResponse = unknown;

/** PATCH /tenants/{id}/activate — response */
export type ActivateResponse = unknown;

/** POST /tenants/{id}/restore — response */
export type RestoreResponse = TenantResponseDTO;

/** GET /tenants/{id}/deletion-status — response */
export type DeletionStatusResponse = TenantDeletionStatusDTO;

/** PATCH /tenants/{tenantId}/admins/{adminId}/role — response */
export type UpdateAdminRoleResponse = unknown;
/** PATCH /tenants/{tenantId}/admins/{adminId}/role — payload */
export interface UpdateAdminRoleBody {
  role?: 'manager' | 'editor' | 'viewer';
}
