// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { IngestResponse, IngestBody, HandoffSummaryForResponse } from './types';

const boteventingestionService = {
  async ingest(body: IngestBody): Promise<IngestResponse> {
    const { data } = await apiClient.post('/api/ingest/bot-events', body);
    return data;
  },

  async handoffSummaryFor(numeroContato: string): Promise<HandoffSummaryForResponse> {
    const { data } = await apiClient.get(`/api/ingest/bot-events/handoff-summary/${numeroContato}`);
    return data;
  },
};

export default boteventingestionService;
