// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type BotEventBatchDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /ingest/bot-events — response */
export type IngestResponse = unknown;
/** POST /ingest/bot-events — payload */
export type IngestBody = BotEventBatchDto;

/** GET /ingest/bot-events/handoff-summary/{numeroContato} — response */
export type HandoffSummaryForResponse = unknown;
