// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetOverviewResponse, GetOverviewParams, GetLeadsOverviewResponse, GetLeadsOverviewParams, GetHomeResponse, GetHomeParams, GetRoiResponse, GetRoiParams, GetSemesterPlanResponse, SubmitBotConfigProposalResponse, SubmitBotConfigProposalBody, GetBotConfigProposalsResponse, GetWhatsAppChannelsResponse, ListWhatsAppConversationsResponse, GetWhatsAppConversationDetailResponse, GetWhatsAppFunnelBoardResponse, GetWhatsAppFunnelMetricsResponse, GetWhatsAppFunnelMetricsParams, GetMyClientsResponse, GetDashboardResponse, GetDashboardParams, GetSnapshotsResponse, GetSnapshotsParams, GetCampaignsResponse, GetCampaignsParams, GetSiteMetricsResponse, GetSiteMetricsParams, GetInstagramOverviewResponse, GetInstagramOverviewParams, GetContentPostsResponse, GetContentPostsParams, GetActivitiesResponse } from './types';

const clientportalService = {
  async getOverview(clientId: string, params: GetOverviewParams = {} as GetOverviewParams): Promise<GetOverviewResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/overview`, { params });
    return data;
  },

  async getLeadsOverview(clientId: string, params: GetLeadsOverviewParams = {} as GetLeadsOverviewParams): Promise<GetLeadsOverviewResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/leads-overview`, { params });
    return data;
  },

  async getHome(clientId: string, params: GetHomeParams = {} as GetHomeParams): Promise<GetHomeResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/home`, { params });
    return data;
  },

  async getRoi(clientId: string, params: GetRoiParams = {} as GetRoiParams): Promise<GetRoiResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/roi`, { params });
    return data;
  },

  async getSemesterPlan(clientId: string): Promise<GetSemesterPlanResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/semester-plan`);
    return data;
  },

  async submitBotConfigProposal(clientId: string, body: SubmitBotConfigProposalBody): Promise<SubmitBotConfigProposalResponse> {
    const { data } = await apiClient.post(`/api/hotel-portal/${clientId}/bot-config-proposals`, body);
    return data;
  },

  async getBotConfigProposals(clientId: string): Promise<GetBotConfigProposalsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/bot-config-proposals`);
    return data;
  },

  async getWhatsAppChannels(clientId: string): Promise<GetWhatsAppChannelsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/whatsapp/channels`);
    return data;
  },

  async listWhatsAppConversations(clientId: string): Promise<ListWhatsAppConversationsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/whatsapp/conversations`);
    return data;
  },

  async getWhatsAppConversationDetail(clientId: string, numeroContato: string): Promise<GetWhatsAppConversationDetailResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/whatsapp/conversations/${numeroContato}`);
    return data;
  },

  async getWhatsAppFunnelBoard(clientId: string): Promise<GetWhatsAppFunnelBoardResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/whatsapp/funnel`);
    return data;
  },

  async getWhatsAppFunnelMetrics(clientId: string, params: GetWhatsAppFunnelMetricsParams = {} as GetWhatsAppFunnelMetricsParams): Promise<GetWhatsAppFunnelMetricsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/whatsapp/funnel/metrics`, { params });
    return data;
  },

  async getMyClients(): Promise<GetMyClientsResponse> {
    const { data } = await apiClient.get('/api/hotel-portal/my-clients');
    return data;
  },

  async getDashboard(clientId: string, params: GetDashboardParams = {} as GetDashboardParams): Promise<GetDashboardResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/dashboard`, { params });
    return data;
  },

  async getSnapshots(clientId: string, params: GetSnapshotsParams = {} as GetSnapshotsParams): Promise<GetSnapshotsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/snapshots`, { params });
    return data;
  },

  async getCampaigns(clientId: string, params: GetCampaignsParams = {} as GetCampaignsParams): Promise<GetCampaignsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/campaigns`, { params });
    return data;
  },

  async getSiteMetrics(clientId: string, params: GetSiteMetricsParams = {} as GetSiteMetricsParams): Promise<GetSiteMetricsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/site-metrics`, { params });
    return data;
  },

  async getInstagramOverview(clientId: string, params: GetInstagramOverviewParams = {} as GetInstagramOverviewParams): Promise<GetInstagramOverviewResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/instagram`, { params });
    return data;
  },

  async getContentPosts(clientId: string, params: GetContentPostsParams = {} as GetContentPostsParams): Promise<GetContentPostsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/content-posts`, { params });
    return data;
  },

  async getActivities(clientId: string): Promise<GetActivitiesResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/activities`);
    return data;
  },
};

export default clientportalService;
