// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetOverviewResponse, GetOverviewParams, GetMyClientsResponse, GetDashboardResponse, GetDashboardParams, GetSnapshotsResponse, GetSnapshotsParams, GetCampaignsResponse, GetCampaignsParams, GetSiteMetricsResponse, GetSiteMetricsParams } from './types';

const clientportalService = {
  async getOverview(clientId: string, params: GetOverviewParams = {} as GetOverviewParams): Promise<GetOverviewResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/overview`, { params });
    return data;
  },

  async getMyClients(): Promise<GetMyClientsResponse> {
    const { data } = await apiClient.get('/api/hotel-portal/my-clients');
    return data;
  },

  async getDashboard(clientId: string, params: GetDashboardParams = {} as GetDashboardParams): Promise<GetDashboardResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/dashboard`, { params });
    return data;
  },

  async getSnapshots(clientId: string, params: GetSnapshotsParams = {} as GetSnapshotsParams): Promise<GetSnapshotsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/snapshots`, { params });
    return data;
  },

  async getCampaigns(clientId: string, params: GetCampaignsParams = {} as GetCampaignsParams): Promise<GetCampaignsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/campaigns`, { params });
    return data;
  },

  async getSiteMetrics(clientId: string, params: GetSiteMetricsParams = {} as GetSiteMetricsParams): Promise<GetSiteMetricsResponse> {
    const { data } = await apiClient.get(`/api/hotel-portal/${clientId}/site-metrics`, { params });
    return data;
  },
};

export default clientportalService;
