// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateBotConfigProposalDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /hotel-portal/{clientId}/overview — response */
export type GetOverviewResponse = unknown;
/** GET /hotel-portal/{clientId}/overview — query params */
export interface GetOverviewParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/leads-overview — response */
export type GetLeadsOverviewResponse = unknown;
/** GET /hotel-portal/{clientId}/leads-overview — query params */
export interface GetLeadsOverviewParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/home — response */
export type GetHomeResponse = unknown;
/** GET /hotel-portal/{clientId}/home — query params */
export interface GetHomeParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/roi — response */
export type GetRoiResponse = unknown;
/** GET /hotel-portal/{clientId}/roi — query params */
export interface GetRoiParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/semester-plan — response */
export type GetSemesterPlanResponse = unknown;

/** POST /hotel-portal/{clientId}/bot-config-proposals — response */
export type SubmitBotConfigProposalResponse = unknown;
/** POST /hotel-portal/{clientId}/bot-config-proposals — payload */
export type SubmitBotConfigProposalBody = CreateBotConfigProposalDto;

/** GET /hotel-portal/{clientId}/bot-config-proposals — response */
export type GetBotConfigProposalsResponse = unknown;

/** GET /hotel-portal/{clientId}/whatsapp/channels — response */
export type GetWhatsAppChannelsResponse = unknown;

/** GET /hotel-portal/{clientId}/whatsapp/conversations — response */
export type ListWhatsAppConversationsResponse = unknown;

/** GET /hotel-portal/{clientId}/whatsapp/conversations/{numeroContato} — response */
export type GetWhatsAppConversationDetailResponse = unknown;

/** GET /hotel-portal/{clientId}/whatsapp/funnel — response */
export type GetWhatsAppFunnelBoardResponse = unknown;

/** GET /hotel-portal/{clientId}/whatsapp/funnel/metrics — response */
export type GetWhatsAppFunnelMetricsResponse = unknown;
/** GET /hotel-portal/{clientId}/whatsapp/funnel/metrics — query params */
export interface GetWhatsAppFunnelMetricsParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/my-clients — response */
export type GetMyClientsResponse = unknown;

/** GET /hotel-portal/{clientId}/dashboard — response */
export type GetDashboardResponse = unknown;
/** GET /hotel-portal/{clientId}/dashboard — query params */
export interface GetDashboardParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/snapshots — response */
export type GetSnapshotsResponse = unknown;
/** GET /hotel-portal/{clientId}/snapshots — query params */
export interface GetSnapshotsParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/campaigns — response */
export type GetCampaignsResponse = unknown;
/** GET /hotel-portal/{clientId}/campaigns — query params */
export interface GetCampaignsParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/site-metrics — response */
export type GetSiteMetricsResponse = unknown;
/** GET /hotel-portal/{clientId}/site-metrics — query params */
export interface GetSiteMetricsParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/instagram — response */
export type GetInstagramOverviewResponse = unknown;
/** GET /hotel-portal/{clientId}/instagram — query params */
export interface GetInstagramOverviewParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/content-posts — response */
export type GetContentPostsResponse = unknown;
/** GET /hotel-portal/{clientId}/content-posts — query params */
export interface GetContentPostsParams {
  month: string;
}

/** GET /hotel-portal/{clientId}/activities — response */
export type GetActivitiesResponse = unknown;
