// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /hotel-portal/{clientId}/overview — response */
export type GetOverviewResponse = unknown;
/** GET /hotel-portal/{clientId}/overview — query params */
export interface GetOverviewParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/my-clients — response */
export type GetMyClientsResponse = unknown;

/** GET /hotel-portal/{clientId}/dashboard — response */
export type GetDashboardResponse = unknown;
/** GET /hotel-portal/{clientId}/dashboard — query params */
export interface GetDashboardParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/snapshots — response */
export type GetSnapshotsResponse = unknown;
/** GET /hotel-portal/{clientId}/snapshots — query params */
export interface GetSnapshotsParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/campaigns — response */
export type GetCampaignsResponse = unknown;
/** GET /hotel-portal/{clientId}/campaigns — query params */
export interface GetCampaignsParams {
  from: string;
  to: string;
}

/** GET /hotel-portal/{clientId}/site-metrics — response */
export type GetSiteMetricsResponse = unknown;
/** GET /hotel-portal/{clientId}/site-metrics — query params */
export interface GetSiteMetricsParams {
  from: string;
  to: string;
}
