// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateLinkResponse, CreateLinkBody, FindLinksResponse, GetLinkStatsResponse, UpdateLinkResponse, UpdateLinkBody, DeleteLinkResponse } from './types';

const whatsapptrackingService = {
  async createLink(clientId: string, body: CreateLinkBody): Promise<CreateLinkResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/whatsapp-links/${clientId}`, body);
    return data;
  },

  async findLinks(clientId: string): Promise<FindLinksResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/whatsapp-links/${clientId}`);
    return data;
  },

  async getLinkStats(clientId: string, linkId: string): Promise<GetLinkStatsResponse> {
    const { data } = await apiClient.get(`/api/admin/hotel-portal/whatsapp-links/${clientId}/${linkId}/stats`);
    return data;
  },

  async updateLink(clientId: string, linkId: string, body: UpdateLinkBody): Promise<UpdateLinkResponse> {
    const { data } = await apiClient.put(`/api/admin/hotel-portal/whatsapp-links/${clientId}/${linkId}`, body);
    return data;
  },

  async deleteLink(clientId: string, linkId: string): Promise<DeleteLinkResponse> {
    const { data } = await apiClient.delete(`/api/admin/hotel-portal/whatsapp-links/${clientId}/${linkId}`);
    return data;
  },
};

export default whatsapptrackingService;
