// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type CreateWhatsAppTrackingLinkDto = Record<string, unknown>;

export type UpdateWhatsAppTrackingLinkDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/whatsapp-links/{clientId} — response */
export type CreateLinkResponse = unknown;
/** POST /admin/hotel-portal/whatsapp-links/{clientId} — payload */
export type CreateLinkBody = CreateWhatsAppTrackingLinkDto;

/** GET /admin/hotel-portal/whatsapp-links/{clientId} — response */
export type FindLinksResponse = unknown;

/** GET /admin/hotel-portal/whatsapp-links/{clientId}/{linkId}/stats — response */
export type GetLinkStatsResponse = unknown;

/** PUT /admin/hotel-portal/whatsapp-links/{clientId}/{linkId} — response */
export type UpdateLinkResponse = unknown;
/** PUT /admin/hotel-portal/whatsapp-links/{clientId}/{linkId} — payload */
export type UpdateLinkBody = UpdateWhatsAppTrackingLinkDto;

/** DELETE /admin/hotel-portal/whatsapp-links/{clientId}/{linkId} — response */
export type DeleteLinkResponse = unknown;
