// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, ListResponse, ListParams, PublishResponse, FindByIdResponse, UpdateResponse, UpdateBody, DeleteResponse } from './types';

const notificationsService = {
  /** Create notification draft (super_admin) */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/notifications', body);
    return data;
  },

  /** List all notifications (super_admin) */
  async list(params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/notifications', { params });
    return data;
  },

  /** Publish notification draft (super_admin) */
  async publish(id: string): Promise<PublishResponse> {
    const { data } = await apiClient.post(`/api/notifications/${id}/publish`);
    return data;
  },

  /** Get notification by ID (super_admin) */
  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/notifications/${id}`);
    return data;
  },

  /** Update notification draft (super_admin) */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/notifications/${id}`, body);
    return data;
  },

  /** Delete notification draft (super_admin) */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/notifications/${id}`);
    return data;
  },
};

export default notificationsService;
