// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateNotificationDTO {
  title: string;
  body: string;
  type: 'manual' | 'event' | 'scheduled';
  scope: 'broadcast' | 'targeted';
  tenant_ids?: string[];
  send_email?: boolean;
  scheduled_at?: string;
}

export interface NotificationResponseDto {
  id: string;
  title: string;
  body: string;
  type: 'manual' | 'event' | 'scheduled';
  scope: 'broadcast' | 'targeted';
  tenant_ids: string[];
  event_key?: string | null;
  metadata?: Record<string, unknown> | null;
  send_email: boolean;
  scheduled_at?: string | null;
  published_at?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface PaginatedNotificationsResponseDto {
  data: NotificationResponseDto[];
  total: number;
}

export interface UpdateNotificationDTO {
  title?: string;
  body?: string;
  scope?: 'broadcast' | 'targeted';
  tenant_ids?: string[];
  send_email?: boolean;
  scheduled_at?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /notifications — response */
export type CreateResponse = NotificationResponseDto;
/** POST /notifications — payload */
export type CreateBody = CreateNotificationDTO;

/** GET /notifications — response */
export type ListResponse = PaginatedNotificationsResponseDto;
/** GET /notifications — query params */
export interface ListParams {
  type?: 'manual' | 'event' | 'scheduled';
  scope?: 'broadcast' | 'targeted';
  published?: boolean;
  page?: number;
  limit?: number;
}

/** POST /notifications/{id}/publish — response */
export type PublishResponse = NotificationResponseDto;

/** GET /notifications/{id} — response */
export type FindByIdResponse = NotificationResponseDto;

/** PATCH /notifications/{id} — response */
export type UpdateResponse = NotificationResponseDto;
/** PATCH /notifications/{id} — payload */
export type UpdateBody = UpdateNotificationDTO;

/** DELETE /notifications/{id} — response */
export type DeleteResponse = unknown;
