// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateNotificationDTO {
  title: string;
  body: string;
  type: 'manual' | 'event' | 'scheduled';
  scope: 'broadcast' | 'targeted';
  tenant_ids?: string[];
  send_email?: boolean;
  scheduled_at?: string;
}

export interface UpdateNotificationDTO {
  title?: string;
  body?: string;
  scope?: 'broadcast' | 'targeted';
  tenant_ids?: string[];
  send_email?: boolean;
  scheduled_at?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /notifications — response */
export type CreateResponse = unknown;
/** POST /notifications — payload */
export type CreateBody = CreateNotificationDTO;

/** GET /notifications — response */
export type ListResponse = unknown;
/** GET /notifications — query params */
export interface ListParams {
  type?: 'manual' | 'event' | 'scheduled';
  scope?: 'broadcast' | 'targeted';
  published?: boolean;
  page?: number;
  limit?: number;
}

/** POST /notifications/{id}/publish — response */
export type PublishResponse = unknown;

/** GET /notifications/{id} — response */
export type FindByIdResponse = unknown;

/** PATCH /notifications/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /notifications/{id} — payload */
export type UpdateBody = UpdateNotificationDTO;

/** DELETE /notifications/{id} — response */
export type DeleteResponse = unknown;
