// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { OverviewResponse, ConnectResponse, ConnectBody, SaveRoomMapResponse, SaveRoomMapBody, SetReconcile2xResponse, SetReconcile2xBody, ReconcileNowResponse } from './types';

const motorchannelService = {
  async overview(tenantId: string): Promise<OverviewResponse> {
    const { data } = await apiClient.get(`/api/motor/${tenantId}/canais`);
    return data;
  },

  async connect(tenantId: string, body: ConnectBody): Promise<ConnectResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/canais/connect`, body);
    return data;
  },

  async saveRoomMap(tenantId: string, body: SaveRoomMapBody): Promise<SaveRoomMapResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/canais/room-map`, body);
    return data;
  },

  async setReconcile2x(tenantId: string, body: SetReconcile2xBody): Promise<SetReconcile2xResponse> {
    const { data } = await apiClient.put(`/api/motor/${tenantId}/canais/reconcile-2x`, body);
    return data;
  },

  async reconcileNow(tenantId: string): Promise<ReconcileNowResponse> {
    const { data } = await apiClient.post(`/api/motor/${tenantId}/canais/reconcile`);
    return data;
  },
};

export default motorchannelService;
