// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type ConnectChannelAdminDto = Record<string, unknown>;

export type SaveRoomMapDto = Record<string, unknown>;

export type Reconcile2xDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /motor/{tenantId}/canais — response */
export type OverviewResponse = unknown;

/** POST /motor/{tenantId}/canais/connect — response */
export type ConnectResponse = unknown;
/** POST /motor/{tenantId}/canais/connect — payload */
export type ConnectBody = ConnectChannelAdminDto;

/** PUT /motor/{tenantId}/canais/room-map — response */
export type SaveRoomMapResponse = unknown;
/** PUT /motor/{tenantId}/canais/room-map — payload */
export type SaveRoomMapBody = SaveRoomMapDto;

/** PUT /motor/{tenantId}/canais/reconcile-2x — response */
export type SetReconcile2xResponse = unknown;
/** PUT /motor/{tenantId}/canais/reconcile-2x — payload */
export type SetReconcile2xBody = Reconcile2xDto;

/** POST /motor/{tenantId}/canais/reconcile — response */
export type ReconcileNowResponse = unknown;
