// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { UploadResponse, UploadBody, ListResponse, ListParams, FindOneResponse, UpdateResponse, UpdateBody, RemoveResponse } from './types';

const cmsMediaAssetsService = {
  /** Upload a new media asset */
  async upload(body: UploadBody): Promise<UploadResponse> {
    const { data } = await apiClient.post('/api/cms/assets', body);
    return data;
  },

  /** List media assets with filtering */
  async list(params: ListParams = {} as ListParams): Promise<ListResponse> {
    const { data } = await apiClient.get('/api/cms/assets', { params });
    return data;
  },

  /** Get media asset by ID */
  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/cms/assets/${id}`);
    return data;
  },

  /** Update asset metadata (alt_text, metadata) */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/cms/assets/${id}`, body);
    return data;
  },

  /** Delete media asset */
  async remove(id: string): Promise<RemoveResponse> {
    const { data } = await apiClient.delete(`/api/cms/assets/${id}`);
    return data;
  },
};

export default cmsMediaAssetsService;
