// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/assets — response */
export type UploadResponse = unknown;
/** POST /cms/assets — payload */
export interface UploadBody {
  /** File to upload (max 50MB). Supported formats depend on collection configuration. */
  file: string;
  /** Collection ID to upload to (CUID format) */
  collection_id: string;
  /** Alternative text for accessibility (recommended for images) */
  alt_text?: string;
  /** Additional metadata as JSON (optional) */
  metadata?: Record<string, unknown>;
}

/** GET /cms/assets — response */
export type ListResponse = unknown;
/** GET /cms/assets — query params */
export interface ListParams {
  /** Filter by collection CUID */
  collection_id?: string;
  status?: 'processing' | 'ready' | 'failed' | 'archived';
  mime_type?: string;
  page?: number;
  limit?: number;
}

/** GET /cms/assets/{id} — response */
export type FindOneResponse = unknown;

/** PATCH /cms/assets/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /cms/assets/{id} — payload */
export interface UpdateBody {
  alt_text?: string;
  metadata?: Record<string, unknown>;
}

/** DELETE /cms/assets/{id} — response */
export type RemoveResponse = unknown;
