// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ResumeConversationResponse, ResumeConversationBody, MoveStageResponse, MoveStageBody, PauseConversationResponse, PauseConversationBody, ExtendHoldResponse, ExtendHoldBody } from './types';

const adminwhatsappfunnelService = {
  async resumeConversation(tenantId: string, contactId: string, body: ResumeConversationBody): Promise<ResumeConversationResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/whatsapp/funnel/${contactId}/resume`, body);
    return data;
  },

  async moveStage(tenantId: string, contactId: string, body: MoveStageBody): Promise<MoveStageResponse> {
    const { data } = await apiClient.patch(`/api/admin/hotel-portal/${tenantId}/whatsapp/funnel/${contactId}/stage`, body);
    return data;
  },

  async pauseConversation(tenantId: string, contactId: string, body: PauseConversationBody): Promise<PauseConversationResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/whatsapp/funnel/${contactId}/pause`, body);
    return data;
  },

  async extendHold(tenantId: string, contactId: string, body: ExtendHoldBody): Promise<ExtendHoldResponse> {
    const { data } = await apiClient.post(`/api/admin/hotel-portal/${tenantId}/whatsapp/funnel/${contactId}/extend-hold`, body);
    return data;
  },
};

export default adminwhatsappfunnelService;
