// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export type ResumeConversationDto = Record<string, unknown>;

export type FunnelStageChangeDto = Record<string, unknown>;

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/hotel-portal/{tenantId}/whatsapp/funnel/{contactId}/resume — response */
export type ResumeConversationResponse = unknown;
/** POST /admin/hotel-portal/{tenantId}/whatsapp/funnel/{contactId}/resume — payload */
export type ResumeConversationBody = ResumeConversationDto;

/** PATCH /admin/hotel-portal/{tenantId}/whatsapp/funnel/{contactId}/stage — response */
export type MoveStageResponse = unknown;
/** PATCH /admin/hotel-portal/{tenantId}/whatsapp/funnel/{contactId}/stage — payload */
export type MoveStageBody = FunnelStageChangeDto;
