// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { AllResponse, ModuleResponse, UpdateResponse, UpdateBody } from './types';

const tenantSettingsService = {
  /** All settings */
  async all(): Promise<AllResponse> {
    const { data } = await apiClient.get('/api/settings');
    return data;
  },

  /** One module settings (merged values only) */
  async module(module: string): Promise<ModuleResponse> {
    const { data } = await apiClient.get(`/api/settings/${module}`);
    return data;
  },

  /** Update module settings */
  async update(module: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/settings/${module}`, body);
    return data;
  },
};

export default tenantSettingsService;
