// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface SettingDescriptorResponseDto {
  /** Current merged value (tenant override if set, otherwise the default) */
  value: Record<string, unknown>;
  /** Default value used when no tenant override exists */
  default: Record<string, unknown>;
  type: 'boolean' | 'string' | 'number' | 'json';
  scope: 'tenant' | 'superadmin';
  description: string;
}

export interface UpdateModuleSettingsDto {
  /** Partial map of setting key (camelCase) to new value. Only provided keys are written. Unknown keys → 400, superadmin-scoped keys → 403 (tenant route only). */
  values: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /settings — response */
export type AllResponse = Record<string, Record<string, SettingDescriptorResponseDto>>;

/** GET /settings/{module} — response */
export type ModuleResponse = Record<string, unknown>;

/** PATCH /settings/{module} — response */
export type UpdateResponse = Record<string, unknown>;
/** PATCH /settings/{module} — payload */
export type UpdateBody = UpdateModuleSettingsDto;
