// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { AuthenticateAdminResponse, AuthenticateAdminBody, MeResponse, RegisterResponse, RegisterBody, ListAllResponse, UpdateRoleResponse, UpdateRoleBody, DeactivateResponse, ActivateResponse, FindByIdResponse, UpdateResponse, UpdateBody, ScheduleDeletionResponse, ScheduleDeletionBody, RestoreDeletionResponse, GetDeletionStatusResponse } from './types';

const adminManagementService = {
  /** Authenticate administrator */
  async authenticateAdmin(body: AuthenticateAdminBody): Promise<AuthenticateAdminResponse> {
    const { data } = await apiClient.post('/api/admin/authenticate', body);
    return data;
  },

  /** Get authenticated administrator data */
  async me(): Promise<MeResponse> {
    const { data } = await apiClient.get('/api/admin/me');
    return data;
  },

  /** Register a new admin (super_admin or manager) */
  async register(body: RegisterBody): Promise<RegisterResponse> {
    const { data } = await apiClient.post('/api/admin/register', body);
    return data;
  },

  /** List admins (super_admin or manager) */
  async listAll(): Promise<ListAllResponse> {
    const { data } = await apiClient.get('/api/admin/list');
    return data;
  },

  /** Update admin role (super_admin or manager) */
  async updateRole(id: string, body: UpdateRoleBody): Promise<UpdateRoleResponse> {
    const { data } = await apiClient.patch(`/api/admin/${id}/role`, body);
    return data;
  },

  /** Deactivate an admin (super_admin only) */
  async deactivate(id: string): Promise<DeactivateResponse> {
    const { data } = await apiClient.patch(`/api/admin/${id}/deactivate`);
    return data;
  },

  /** Activate an admin (super_admin only) */
  async activate(id: string): Promise<ActivateResponse> {
    const { data } = await apiClient.patch(`/api/admin/${id}/activate`);
    return data;
  },

  /** Get admin by ID (super_admin or manager) */
  async findById(id: string): Promise<FindByIdResponse> {
    const { data } = await apiClient.get(`/api/admin/${id}`);
    return data;
  },

  /** Update admin data (super_admin or manager) */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/admin/${id}`, body);
    return data;
  },

  /** Schedule admin deletion (super_admin only) */
  async scheduleDeletion(id: string, body: ScheduleDeletionBody): Promise<ScheduleDeletionResponse> {
    const { data } = await apiClient.delete(`/api/admin/${id}`, { data: body });
    return data;
  },

  /** Restore admin scheduled for deletion (super_admin only) */
  async restoreDeletion(id: string): Promise<RestoreDeletionResponse> {
    const { data } = await apiClient.post(`/api/admin/${id}/restore-deletion`);
    return data;
  },

  /** Get admin deletion status (super_admin only) */
  async getDeletionStatus(id: string): Promise<GetDeletionStatusResponse> {
    const { data } = await apiClient.get(`/api/admin/${id}/deletion-status`);
    return data;
  },
};

export default adminManagementService;
