// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface AuthAdminDTO {
  /** Administrator email */
  email: string;
  /** Administrator password */
  password: string;
}

export interface AdminResponseDTO {
  /** Admin CUID (25-character identifier) */
  id: string;
  name: string;
  email: string;
  role: 'super_admin' | 'owner' | 'manager' | 'editor' | 'viewer' | 'company_admin';
  active: boolean;
  tenants: Record<string, unknown>[];
  created_at: string;
}

export interface CreateAdminDTO {
  /** Administrator name */
  name: string;
  /** Administrator email */
  email: string;
  /** Administrator password */
  password: string;
  /** Administrator role */
  role?: 'super_admin' | 'owner' | 'manager' | 'editor' | 'viewer' | 'company_admin';
}

export interface AdminListItemDTO {
  /** Admin CUID (25-character identifier) */
  id: string;
  name: string;
  email: string;
  role: 'super_admin' | 'owner' | 'manager' | 'editor' | 'viewer' | 'company_admin';
  active: boolean;
  tenants: Record<string, unknown>[];
  scheduled_for_deletion?: boolean;
  deletion_scheduled_for_at?: string | null;
  created_at: string;
}

export interface UpdateAdminRoleDTO {
  /** New role */
  role: 'super_admin' | 'owner' | 'manager' | 'editor' | 'viewer' | 'company_admin';
}

export interface UpdateAdminDTO {
  /** Administrator name */
  name?: string;
  /** Administrator email */
  email?: string;
  /** Administrator password (super_admin only) */
  password?: string;
}

export interface ScheduleAdminDeletionDTO {
  /** Optional reason for scheduling admin deletion */
  reason?: string;
}

export interface AdminDeletionStatusDTO {
  /** Admin CUID (25-character identifier) */
  id: string;
  active: boolean;
  scheduled_for_deletion: boolean;
  archived_at?: string | null;
  deletion_requested_at?: string | null;
  deletion_scheduled_for_at?: string | null;
  deletion_requested_by?: string | null;
  deletion_reason?: string | null;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /admin/authenticate — response */
export type AuthenticateAdminResponse = unknown;
/** POST /admin/authenticate — payload */
export type AuthenticateAdminBody = AuthAdminDTO;

/** GET /admin/me — response */
export type MeResponse = AdminResponseDTO;

/** POST /admin/register — response */
export type RegisterResponse = unknown;
/** POST /admin/register — payload */
export type RegisterBody = CreateAdminDTO;

/** GET /admin/list — response */
export type ListAllResponse = AdminListItemDTO[];

/** PATCH /admin/{id}/role — response */
export type UpdateRoleResponse = unknown;
/** PATCH /admin/{id}/role — payload */
export type UpdateRoleBody = UpdateAdminRoleDTO;

/** PATCH /admin/{id}/deactivate — response */
export type DeactivateResponse = unknown;

/** PATCH /admin/{id}/activate — response */
export type ActivateResponse = unknown;

/** GET /admin/{id} — response */
export type FindByIdResponse = AdminResponseDTO;

/** PATCH /admin/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /admin/{id} — payload */
export type UpdateBody = UpdateAdminDTO;

/** DELETE /admin/{id} — response */
export type ScheduleDeletionResponse = unknown;
/** DELETE /admin/{id} — payload */
export type ScheduleDeletionBody = ScheduleAdminDeletionDTO;

/** POST /admin/{id}/restore-deletion — response */
export type RestoreDeletionResponse = AdminResponseDTO;

/** GET /admin/{id}/deletion-status — response */
export type GetDeletionStatusResponse = AdminDeletionStatusDTO;
