// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, FindAllParams, UpdateResponse, UpdateBody, DeleteResponse } from './types';

const analyticsReportsService = {
  /** Create analytics report link (phone → URL) */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/reports', body);
    return data;
  },

  /** List all analytics report links */
  async findAll(params: FindAllParams = {} as FindAllParams): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/reports', { params });
    return data;
  },

  /** Update analytics report link */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.patch(`/api/reports/${id}`, body);
    return data;
  },

  /** Delete analytics report link */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/reports/${id}`);
    return data;
  },
};

export default analyticsReportsService;
