// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateAnalyticsReportDto {
  /** Phone number (unique identifier) */
  phone: string;
  /** Analytics report URL */
  url: string;
  /** Optional label for identification */
  label?: string;
}

export interface UpdateAnalyticsReportDto {
  /** Phone number (unique identifier) */
  phone?: string;
  /** Analytics report URL */
  url?: string;
  /** Optional label for identification */
  label?: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /reports — response */
export type CreateResponse = unknown;
/** POST /reports — payload */
export type CreateBody = CreateAnalyticsReportDto;

/** GET /reports — response */
export type FindAllResponse = unknown;
/** GET /reports — query params */
export interface FindAllParams {
  limit?: number;
  page?: number;
}

/** PATCH /reports/{id} — response */
export type UpdateResponse = unknown;
/** PATCH /reports/{id} — payload */
export type UpdateBody = UpdateAnalyticsReportDto;

/** DELETE /reports/{id} — response */
export type DeleteResponse = unknown;
