// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateResponse, CreateBody, FindAllResponse, FindAllParams, UpdateResponse, UpdateBody, FindOneResponse, DeleteResponse, UploadAvatarResponse, UploadAvatarBody } from './types';

const cmsAuthorManagementService = {
  /** Create a new author */
  async create(body: CreateBody): Promise<CreateResponse> {
    const { data } = await apiClient.post('/api/cms/authors', body);
    return data;
  },

  /** List all authors with optional filters */
  async findAll(params: FindAllParams = {} as FindAllParams): Promise<FindAllResponse> {
    const { data } = await apiClient.get('/api/cms/authors', { params });
    return data;
  },

  /** Update author information */
  async update(id: string, body: UpdateBody): Promise<UpdateResponse> {
    const { data } = await apiClient.put(`/api/cms/authors/${id}`, body);
    return data;
  },

  /** Get a single author by ID */
  async findOne(id: string): Promise<FindOneResponse> {
    const { data } = await apiClient.get(`/api/cms/authors/${id}`);
    return data;
  },

  /** Delete an author (prevents deletion if author has published articles) */
  async delete(id: string): Promise<DeleteResponse> {
    const { data } = await apiClient.delete(`/api/cms/authors/${id}`);
    return data;
  },

  /** Assign an existing media asset as the author avatar */
  async uploadAvatar(id: string, body: UploadAvatarBody): Promise<UploadAvatarResponse> {
    const { data } = await apiClient.post(`/api/cms/authors/${id}/avatar`, body);
    return data;
  },
};

export default cmsAuthorManagementService;
