// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateAuthorDTO {
  /** Author first name */
  firstName: string;
  /** Author last name */
  lastName: string;
  /** Author biography */
  biography?: string;
  /** Avatar MediaAsset ID (CUID de 25 caracteres) */
  avatarId?: string;
}

export interface AuthorAvatarResponseDTO {
  /** Media asset CUID */
  id: string;
  /** Public asset URL */
  url: string;
  /** Storage object key */
  storage_key: string;
  /** Original file name */
  filename: string;
  /** Detected MIME type */
  mime_type: string;
  /** File size in bytes */
  file_size: number;
  /** Image width in pixels */
  width?: number | null;
  /** Image height in pixels */
  height?: number | null;
  /** Alternative text */
  alt_text?: string | null;
}

export interface AuthorResponseDTO {
  /** Author CUID */
  id: string;
  /** Author first name */
  first_name: string;
  /** Author last name */
  last_name: string;
  /** Computed full name */
  full_name: string;
  /** Author biography */
  biography?: string | null;
  /** Avatar MediaAsset CUID */
  avatar_id?: string | null;
  /** Tenant CUID owner of this author */
  tenant_id: string;
  /** Active status */
  active: boolean;
  /** Creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
  /** Expanded avatar payload when available */
  avatar?: AuthorAvatarResponseDTO;
}

export interface AuthorPaginationResponseDTO {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface PaginatedAuthorsResponseDTO {
  data: AuthorResponseDTO[];
  pagination: AuthorPaginationResponseDTO;
}

export interface UpdateAuthorDTO {
  /** Author first name */
  firstName?: string;
  /** Author last name */
  lastName?: string;
  /** Author biography */
  biography?: string;
  /** Avatar MediaAsset ID (CUID de 25 caracteres) */
  avatarId?: string;
  /** Active status */
  active?: boolean;
}

export interface SuccessMessageResponseDTO {
  /** Operation result message */
  message: string;
}

export interface AssignAuthorAvatarDTO {
  /** Existing MediaAsset CUID to assign as the author avatar */
  avatarId: string;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /cms/authors — response */
export type CreateResponse = AuthorResponseDTO;
/** POST /cms/authors — payload */
export type CreateBody = CreateAuthorDTO;

/** GET /cms/authors — response */
export type FindAllResponse = PaginatedAuthorsResponseDTO;
/** GET /cms/authors — query params */
export interface FindAllParams {
  /** Filter by active status */
  active?: boolean;
  /** Page number (starts at 1) */
  page?: number;
  /** Items per page */
  limit?: number;
}

/** PUT /cms/authors/{id} — response */
export type UpdateResponse = AuthorResponseDTO;
/** PUT /cms/authors/{id} — payload */
export type UpdateBody = UpdateAuthorDTO;

/** GET /cms/authors/{id} — response */
export type FindOneResponse = AuthorResponseDTO;

/** DELETE /cms/authors/{id} — response */
export type DeleteResponse = SuccessMessageResponseDTO;

/** POST /cms/authors/{id}/avatar — response */
export type UploadAvatarResponse = AuthorResponseDTO;
/** POST /cms/authors/{id}/avatar — payload */
export type UploadAvatarBody = AssignAuthorAvatarDTO;
