// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { LookupResponse, LookupParams } from './types';

const analyticsReportsPublicService = {
  /** Look up analytics report URL by phone number */
  async lookup(params: LookupParams = {} as LookupParams): Promise<LookupResponse> {
    const { data } = await apiClient.get('/api/reports/lookup', { params });
    return data;
  },
};

export default analyticsReportsPublicService;
