// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /reports/lookup — response */
export type LookupResponse = unknown;
/** GET /reports/lookup — query params */
export interface LookupParams {
  /** Phone number to look up */
  phone: string;
}
