// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetAvailabilityResponse, GetAvailabilityParams } from './types';

const publicAppointmentsService = {
  /** Get available appointment slots for a date */
  async getAvailability(params: GetAvailabilityParams = {} as GetAvailabilityParams): Promise<GetAvailabilityResponse> {
    const { data } = await apiClient.get('/api/leads/appointments/availability', { params });
    return data;
  },
};

export default publicAppointmentsService;
