// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /leads/appointments/availability — response */
export interface GetAvailabilityResponse {
  data?: {
    slots?: {
      startTime?: string;
      endTime?: string;
      date?: string;
      availableCapacity?: number;
      isAvailable?: boolean;
    }[];
  };
  status?: number;
}
/** GET /leads/appointments/availability — query params */
export interface GetAvailabilityParams {
  /** Date in ISO format (YYYY-MM-DD) */
  date: string;
}
