// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { ReceiveWebhookResponse } from './types';

const bookingwebhookService = {
  async receiveWebhook(tenantId: string): Promise<ReceiveWebhookResponse> {
    const { data } = await apiClient.post(`/api/webhooks/booking-engine/${tenantId}`);
    return data;
  },
};

export default bookingwebhookService;
