// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /webhooks/booking-engine/{tenantId} — response */
export type ReceiveWebhookResponse = unknown;
