// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { HandleStripeWebhookResponse } from './types';

const unifiedWebhooksService = {
  /** Unified Stripe webhook endpoint (handles both B2B and B2C) */
  async handleStripeWebhook(): Promise<HandleStripeWebhookResponse> {
    const { data } = await apiClient.post('/api/webhooks/stripe');
    return data;
  },
};

export default unifiedWebhooksService;
