// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /webhooks/stripe — response */
export type HandleStripeWebhookResponse = unknown;
