// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { CreateSmtpServerResponse, CreateSmtpServerBody, FindSmtpServersResponse } from './types';

const configService = {
  /** Create SMTP server */
  async createSmtpServer(body: CreateSmtpServerBody): Promise<CreateSmtpServerResponse> {
    const { data } = await apiClient.post('/api/mailer/smtp-server', body);
    return data;
  },

  /** List SMTP servers */
  async findSmtpServers(): Promise<FindSmtpServersResponse> {
    const { data } = await apiClient.get('/api/mailer/smtp-server');
    return data;
  },
};

export default configService;
