// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface CreateSmtpServerDTO {
  /** SMTP server name */
  name: string;
  /** Email associated with the SMTP server */
  email: string;
  /** SMTP provider type */
  provider: 1 | 2;
  /** Set as default server */
  default?: boolean;
  /** SMTP settings (required if provider is SMTP) */
  smtp?: Record<string, unknown>;
  /** API settings (required if provider uses API) */
  api?: Record<string, unknown>;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** POST /mailer/smtp-server — response */
export type CreateSmtpServerResponse = unknown;
/** POST /mailer/smtp-server — payload */
export type CreateSmtpServerBody = CreateSmtpServerDTO;

/** GET /mailer/smtp-server — response */
export type FindSmtpServersResponse = unknown;
