// Auto-generated by nextjs-openapi-codegen — do not edit manually
import apiClient from '@/src/infraestructure/axios/api';
import type { GetGlobalConfigResponse, UpsertGlobalConfigResponse, UpsertGlobalConfigBody, ListCategoriesResponse, CreateCategoryResponse, CreateCategoryBody, UpdateCategoryResponse, UpdateCategoryBody, DeleteCategoryResponse, GetProductsByCategoryResponse, UpdateProductFeesResponse, UpdateProductFeesBody } from './types';

const adminBcFeeConfigService = {
  /** Buscar taxa global do tenant */
  async getGlobalConfig(): Promise<GetGlobalConfigResponse> {
    const { data } = await apiClient.get('/api/b2c/fees/global');
    return data;
  },

  /** Criar ou atualizar taxa global do tenant */
  async upsertGlobalConfig(body: UpsertGlobalConfigBody): Promise<UpsertGlobalConfigResponse> {
    const { data } = await apiClient.put('/api/b2c/fees/global', body);
    return data;
  },

  /** Listar categorias de produto com suas taxas */
  async listCategories(): Promise<ListCategoriesResponse> {
    const { data } = await apiClient.get('/api/b2c/fees/categories');
    return data;
  },

  /** Criar categoria de produto */
  async createCategory(body: CreateCategoryBody): Promise<CreateCategoryResponse> {
    const { data } = await apiClient.post('/api/b2c/fees/categories', body);
    return data;
  },

  /** Atualizar categoria de produto */
  async updateCategory(id: string, body: UpdateCategoryBody): Promise<UpdateCategoryResponse> {
    const { data } = await apiClient.patch(`/api/b2c/fees/categories/${id}`, body);
    return data;
  },

  /** Remover categoria de produto */
  async deleteCategory(id: string): Promise<DeleteCategoryResponse> {
    const { data } = await apiClient.delete(`/api/b2c/fees/categories/${id}`);
    return data;
  },

  /** Listar produtos de uma categoria */
  async getProductsByCategory(id: string): Promise<GetProductsByCategoryResponse> {
    const { data } = await apiClient.get(`/api/b2c/fees/categories/${id}/products`);
    return data;
  },

  /** Configurar taxas de um produto específico */
  async updateProductFees(productId: string, body: UpdateProductFeesBody): Promise<UpdateProductFeesResponse> {
    const { data } = await apiClient.patch(`/api/b2c/fees/products/${productId}`, body);
    return data;
  },
};

export default adminBcFeeConfigService;
