// Auto-generated by nextjs-openapi-codegen — do not edit manually

// ─── Shared schemas ─────────────────────────────────────────────────────────

export interface UpsertFeeConfigDTO {
  /** Chip cost percentual global (ex: 2.5 = 2.5% sobre o preço do produto). Aplicado a todos os produtos sem override. */
  chipCostPercent: number;
  /** Frete fixo global em centavos (ex: 1500 = R$15,00). Aplicado a produtos físicos sem override. */
  shippingFee: number;
}

export interface CreateProductCategoryDTO {
  /** Nome da categoria */
  name: string;
  /** Slug único da categoria (letras minúsculas, números e hífens) */
  slug: string;
  /** Chip cost % para esta categoria. null = herda da taxa global do tenant. */
  chipCostPercent?: number | null;
  /** Frete fixo em centavos para esta categoria. null = herda da taxa global. */
  shippingFee?: number | null;
}

export interface UpdateProductCategoryDTO {
  name?: string;
  chipCostPercent?: number | null;
  shippingFee?: number | null;
  active?: boolean;
}

export interface UpdateProductFeesDTO {
  /** ID da categoria do produto. null = sem categoria (usa taxa global). */
  categoryId?: string | null;
  /** Override de chip cost % para este produto específico. null = remove override (herda da categoria/global). */
  chipCostOverride?: number | null;
  /** Override de frete em centavos para este produto. null = remove override. */
  shippingFeeOverride?: number | null;
  /** Se o produto é físico e requer envio (books, tabs). */
  requiresShipping?: boolean;
}

// ─── Operation types ────────────────────────────────────────────────────────

/** GET /b2c/fees/global — response */
export type GetGlobalConfigResponse = unknown;

/** PUT /b2c/fees/global — response */
export type UpsertGlobalConfigResponse = unknown;
/** PUT /b2c/fees/global — payload */
export type UpsertGlobalConfigBody = UpsertFeeConfigDTO;

/** GET /b2c/fees/categories — response */
export type ListCategoriesResponse = unknown;

/** POST /b2c/fees/categories — response */
export type CreateCategoryResponse = unknown;
/** POST /b2c/fees/categories — payload */
export type CreateCategoryBody = CreateProductCategoryDTO;

/** PATCH /b2c/fees/categories/{id} — response */
export type UpdateCategoryResponse = unknown;
/** PATCH /b2c/fees/categories/{id} — payload */
export type UpdateCategoryBody = UpdateProductCategoryDTO;

/** DELETE /b2c/fees/categories/{id} — response */
export type DeleteCategoryResponse = unknown;

/** GET /b2c/fees/categories/{id}/products — response */
export type GetProductsByCategoryResponse = unknown;

/** PATCH /b2c/fees/products/{productId} — response */
export type UpdateProductFeesResponse = unknown;
/** PATCH /b2c/fees/products/{productId} — payload */
export type UpdateProductFeesBody = UpdateProductFeesDTO;
